### ISSUE TITLE
Article based on @njtierney's "Magic reprex" blog post

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#101]
@njtierney This is so nifty:

https://www.njtierney.com/post/2017/01/11/magic-reprex/

How do you feel about a version of that being an article in the reprex website? If you are positive, do you have any willingness to make the PR or do you know someone who might want the chance to practice?

**Comment by njtierney** [comment]
Hi Jenny, Thanks! :)

Very happy to put this onto the reprex website, would you like me to change anything? I was thinking perhaps a comment at the start like "this article was originally posted at Nick Tierney's blog, [here](https://www.njtierney.com/post/2017/01/11/magic-reprex/)." Or something like that?

For the PR, would it just be a pull request with a vignette plus rendering the website with pkgdown?

**Comment by jennybc** [comment]
Yes, definitely link back to your blog, as you say above!

It should be an article in `vignettes/articles/`. The readxl website has an example of an `.Rmd` in this location. This way it won't go to CRAN, which makes life easier. I would prefer to do the pkgdown rendering myself, so a PR with just the source files would be great 🙏

**Comment by njtierney** [comment]
OK done, I think!

Please feel free to change the preamble, I've written

> This article was originally posted on [Nick Tierney's blog](https://www.njtierney.com/post/2017/01/11/magic-reprex/), and has been contributed here to help spread the good word about `reprex`! :) - **Nick Tierney**

But I'm happy for wording to be changed, and am very open to feedback if you'd like me to change this or anything else :)

**Comment by njtierney** [comment]
ALSO, so cool that this is issue 101
