### ISSUE TITLE
Argument / option to apply re-style code with styler

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#108]
I'm switching from `formatR::tidy_source()` to [`styler::style_text()`](https://github.com/krlmlr/styler#readme) (#94). The most specific motivation is styler's ability to handle tidy eval code. Currently reprex re-styles code that came via expression, because the srcref approach mutilates leading whitespace.

Now that I'm playing with styler I wonder if reprex should re-style **all** code. At least by default? 

I could add an argument to control re-styling, that defaults to `TRUE`. BTW I have plans to make several arguments like this settable via an option, so they're easy to set in a startup file.

This would have the effect of putting good code style in front of the eyeballs of all reprex authors and consumers.

cc @hadley @jimhester

**Comment by hadley** [comment]
I'm generally not in favour of restyling code, but here it might make sense.

**Comment by jimhester** [comment]
I actually don't think we need to style the code in any case, I am going to send a PR to retrieve the original formatting for expressions via the 'wholeSrcref' attribute in the captured expression.

**Comment by jimhester** [comment]
https://github.com/tidyverse/reprex/pull/112 has adjusted code that preserves the original expression formatting.

I would turn off automatic formatting for expressions and have reformatting only as an option (disabled by default).

**Comment by jennybc** [comment]
#112 is now included in #114, fyi.

I either have to restyle expression code or remove the common leading whitespace, because preserving the whitespace verbatim, breaks the use of roxygen comments to insert text.

---

Input with natural indenting, i.e. what RStudio wants you to do:

``` r
reprex({
  #' # A Big Heading
  #'
  #' Look at my cute example. I love the
  #' [reprex](https://github.com/tidyverse/reprex#readme) package!
  y <- 1:4
  mean(y)
})
```

Output

``` r
#' # A Big Heading
#'
#' Look at my cute example. I love the
#' [reprex](https://github.com/tidyverse/reprex#readme) package!
y <- 1:4
mean(y)
#> [1] 2.5
```

---

Input with manual (lack of) indenting, so roxygen comments still work:

``` r
reprex({
#' # A Big Heading
#'
#' Look at my cute example. I love the
#' [reprex](https://github.com/tidyverse/reprex#readme) package!
y <- 1:4
mean(y)
})
```

Output

A Big Heading
=============

Look at my cute example. I love the [reprex](https://github.com/tidyverse/reprex#readme) package!

``` r
y <- 1:4
mean(y)
#> [1] 2.5
```

**Comment by jennybc** [comment]
Here's my new proposal: add an argument for code re-styling (and give it the option treatment soon) and have it default to `FALSE` in general and `TRUE` for expression input.

**Comment by jimhester** [comment]
I think in that case you should just remove the common leading whitespace. `glue::trim()` would be an easy way to do the trimming, or you can do it with a regex 

``` r
x <- c(
  "  some text",
  "    some indented text",
  "  some more text")

trim_whitespace <- function(x) {
  m <- regexpr("^(\\s*)", x)
  leading_whitespace <- regmatches(x, m)
  num <- min(nchar(leading_whitespace))
  substring(x, num + 1)
}
trim_whitespace(x)
#> [1] "some text"            "  some indented text" "some more text"

y <- c("text without leading whitespace")
trim_whitespace(y)
#> [1] "text without leading whitespace"

z <- c(
  "text without leading whitespace",
  "  test with leading whitespace"
)
trim_whitespace(z)
#> [1] "text without leading whitespace" "  test with leading whitespace"
```
