### ISSUE TITLE
Enable package management reminders/best practice

### ISSUE THREAD

**Issue by pgensler** [tidyverse/reprex#113]
Is there any good reason why the pacman package is not used in tandem with reprex? I can understand why the need to be explicit with loading is good to see what exactly the messages are are startup, but it can be bothersome to write out 6 or more `library` or `require` calls to simply load packages for a `reprex`. In my experience creating reprex's, I have found that while it is useful to explicitly state the packages loaded for a given example, I think it would save much amount of code to utilize existing functions so that you can easily load up libraries as such, and easily unload. Below is an example where I had a hard time finding base code to load and unload an r package in one script, yet the `pacman::p_unload(dplyr)` was incredibly useful to make a very succinct script.

Related issue on package messages not appearing in `pacman`:
https://github.com/trinker/pacman/issues/99

One side note is that while it looks that dplyr has an odd character �, the reprex rendered HTML is OK:
![image](https://user-images.githubusercontent.com/7308115/30840431-d93710ee-a23c-11e7-8d67-abb239fd6bb0.png)

``` r
##########################

data_t_five <- structure(c(0L, 2L, 3L, 9L, 8L, 0L, 0L, 14L, 0L, 3L, 1L, 3L, 
                           0L, 9L, 3L, 3L, 10L, 13L, 14L, 14L, 1L, 5L, 8L, 10L, 12L, 0L, 
                           1L, 0L, 1L, 2L, 5L, 10L, 13L, 15L, 14L, 0L, 0L, 3L, 8L, 2L, 0L, 
                           1L, 6L, 3L, 7L, 0L, 1L, 2L, 1L, 12L, 0L, 3L, 3L, 1L, 5L, 0L, 
                           0L, 1L, 1L, 2L, 0L, 2L, 6L, 9L, 3L, 3L, 1L, 7L, 14L, 15L, 0L, 
                           0L, 2L, 15L, 3L, 0L, 6L, 6L, 10L, 14L, 3L, 1L, 6L, 13L, 15L, 
                           0L, 0L, 0L, 4L, 3L, 0L, 6L, 3L, 0L, 5L, 6L, 11L, 15L, 16L, 15L, 
                           1L, 1L, 1L, 2L, 3L, 1L, 0L, 0L, 10L, 7L, 0L, 1L, 8L, 2L, 3L, 
                           0L, 0L, 1L, 0L, 2L, 1L, 2L, 1L, 2L, 3L), .Dim = c(5L, 25L), .Dimnames = list(
                             c("Jan", "Feb", "Mar", "Apr", "May"), NULL))
#library(tidyr)
#library(magrittr)
#library(tibble)
#library(dplyr)
pacman::p_load(tidyr, magrittr, tibble, dplyr)
first_five_mod = data.frame(data_t_five)
##Verify 'rownames' is a column name
f=first_five_mod %>%
  rownames_to_column %>% 
  gather(var, value, -rowname)
colnames(f)
#> [1] "rowname" "var"     "value"
##Try to filter df for rowname = "Jan" without explicit dplyr
##dplyr was not loaded so it tried to call filter from package stats, which threw
## an error
pacman::p_unload(dplyr)
#> The following packages have been unloaded:
#> dplyr
f=first_five_mod %>%
  rownames_to_column %>% 
  gather(var, value, -rowname) %>%
  filter(rowname == "Jan")
#> Warning in data.matrix(data): NAs introduced by coercion

#> Warning in data.matrix(data): NAs introduced by coercion
#> Error in filter(., rowname == "Jan"): object 'rowname' not found

##Works using explicict dplyr call
f=first_five_mod %>%
  rownames_to_column %>% 
  gather(var, value, -rowname) %>%
  dplyr::filter(rowname == "Jan")

########################
```

**Comment by jennybc** [comment]
I don't quite follow. Are you saying that reprex prevents you from using pacman as you like? I think it's completely agnostic on this point.

**Comment by pgensler** [comment]
I'm curious what exactly the `reprex` way of package management is, or if there is even one, as users like myself are using multiple packages for analysis, and it can be quite tedious to have multiple lines of `library` calls when you have multiple packages loaded, so I'm curious why the **`pacman` package is not strongly encouraged to be used in tandem with `reprex`**, as it **simplifies** the beginning of the script, and the function naming seems to follow the tidyverse style per the quick reference table: https://github.com/trinker/pacman

It seems like it would complement the `reprex` package well, so is the reason because the external dependency, or a preference of using base r functions??

 Maybe this is just me, but if you want a reprex script to be as succinct, and simple as possible, then wouldn't it make sense to have a simple one-liner(as the code above), rather than 10 library calls at the beginning of the script? The only argument I can see for not utilizing it is that `pacman` suppresses all startup messages with no way of enabling them at this point, but explicitly using library calls would force the package startup messages to be shown.

**Comment by jennybc** [comment]
You can just use `pacman::p_load(tidyr, magrittr, tibble, dplyr)` as the first line of your reprex. reprex just runs code and has no opinion about whether you use `library()` to load packages or `pacman::p_load()`.

If you're asking about philosophy or documentation, then no I don't want to officially tie reprex to pacman. I don't have it installed, so to run your reprex above, I'd have to install pacman just to load four packages in one line instead of 4. Plus, in this *specific* case, I'd probably use `library(tidyverse)` as a shortcut, which also now suppresses the tidyverse startup messaging (https://github.com/tidyverse/reprex/pull/100). Finally, I have strong objections to `pacman::p_load()`'s ability to *install* packages on my system. I don't think package installation belongs in a script and definitely not in a reprex you're asking lots of other people to run.

Most of my reprexes involve a small number of packages, due to the nature of small self-contained examples. I'm wondering if you have some other use case where it's common to load and possibly install/update a large number of packages?

**Comment by pgensler** [comment]
To be clear, `pacman::p_load()` is intended for loading a library, so I can understand your concern with regards to its behavior to installing a package.
On the contrary, if I am using a specialized package, I can see the value in using  `package::function`, but I think it would probably be best to outline that in the readme as a best practice for reprex's.

If that is truly what makes you have a strong objection, I would encourage you to look at the source code for a PR, as it seems it may be incomplete per line 64: <https://github.com/trinker/pacman/blob/master/R/p_load.R>. Most of what I have been doing has required 4-5 other packages as such, because I would like to utilize special functions to perform certain munging tasks (like reading in JSON, and cleaning text) from packages like `textclean` or `janitor` or `tidyjson`. JSON/web scraping is a bit interesting as there a definitely quite a few packages to work with like ```rvest``` or ```purr```.


Something to note with the above reprex supplied is that was actually part of an issue where the user I was working with did not know to show the packages loaded, and he actually had multiple packages loaded from the <https://github.com/business-science> library, but I think was a little more frustrated about how to create a reprex, and simply copied and pasted code. Are you accepting PR's by chance? Personally, I think this would make a great example on how to create a ```reprex``` when using other's packages. When I am trying to create a reprex, I think the readme can be a bit confusing personally.

**Comment by jennybc** [comment]
There's no debate that a reprex has to be self-contained, so the only question is who writes the code to load the necessary packages: the user or reprex. There's an existing PR (but still a discussion, really) about this: https://github.com/tidyverse/reprex/pull/93. I think that might end with an argument and related option to insert `library()` calls into the reprex source for all the currently loaded packages.

Sure, I review and accept PRs! I'm happy to hear ideas on how to make the docs better. I certainly don't want the README to be confusing.

**Comment by jennybc** [comment]
I'm pushing towards a release. This was a productive discussion but doesn't require any specific action.

**Comment by jennybc** [comment]
I see Docker as a pretty heavyweight solution here. Or, rather, you're tackling a very different problem. So, yes, this feels complementary to reprex.

What you're describing sounds like the kind of usage @jimhester blogs about in [Docker for R Package Development](http://www.jimhester.com/2017/10/13/docker/).

**Comment by pgensler** [comment]
I view my image more of a sandbox for analysts, not a package dev environment. Building the dockerfile is very different than what Jim blogged about (though your blog was incredibly useful). CI is a great example on this, as I think Travis is not really meant for this, but rather GitLabs/Docker Hub are.

maybe working with rocker and seeing if they want to host an image purely for reprex's is not a bad idea? somewhat more complicated, but something to consider with the expanding pkg ecosystem.

cc @jimhester
