### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#117]
Consolidating + closing these two issues:

  * Write a blog post (#62). This issue was created around the first CRAN release in January 2017 and ... I never did that.
  * "Pull out how to make a reprex into own article" (#79) I cc'ed @hadley when issue was created, so perhaps his idea.

Existing docs:

  * [GitHub README](https://github.com/tidyverse/reprex#readme) = [landing page of pkgdown site](http://reprex.tidyverse.org/index.html)
  * [Vignette](http://reprex.tidyverse.org/articles/reprex.html). Not linked from anywhere, not part of the CRAN version. Does this even need to exist in light of the README/index page and the tidyverse page?
  * [Get help! section of tidyverse.org](https://www.tidyverse.org/help/) now covers reprex.
  * [Magic reprex blog post by N. Tierney](http://reprex.tidyverse.org/articles/articles/magic-reprex.html), included in pkgdown site as an article.

@hadley any thoughts about

  * anything new needed? blog post?
  * existing stuff should be merged? Perhaps should kill existing vignette.

**Comment by hadley** [comment]
Maybe Nick's post could become the main content for the blog post? (Which I think is still worthwhile)

I agree that vignette could probably go away now

**Comment by jennybc** [comment]
Upon re-reading, I decided to keep the vignette. But I edited it.

Upon the next CRAN release, I am happy to contribute a blog post.
