### ISSUE TITLE
reprex interferes with utils::capture.output()

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/reprex#118]
`reprex` appears to interfere with `utils::capture.output()`. 

Expected behavior: a `reprex` run of the code below works as in the `R` console, printing nothing nothing during the `msg` assignment and then storing the message `"hi"` into the `msg` variable.

Observed behavior (indicated below): the `"hi"` is instead printed early and the `msg` variable receives an empty string.

Code:

```r
packageVersion("reprex")
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
print(paste('msg is:', msg))
```

`reprex` result:

``` r
packageVersion("reprex")
#> [1] '0.1.1'
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
#> hi
print(paste('msg is:', msg))
#> [1] "msg is: "
```

**Comment by jennybc** [comment]
reprex just prepares an `.R` script to process with `rmarkdown::render()`. There's a lot of pre/post processing involved, so reprex can introduce behaviours, for sure.

But in this case, I don't think reprex has anything to do with it. If I make a fresh `.Rmd` and drop your example code into a chunk and render it ... I get your same result. So I believe it's an rmarkdown behaviour and something I can't change.

I suspect it has something to do with knitr changing the behaviour of `capture.output()`. If there are, say, chunk options we can use to induce "interactive" behaviour under knit/render, then we'd be able to get what you want.

**Comment by JohnMount** [comment]
Thanks. I suspected as much and also filed as [`knitr` issue 1437](https://github.com/yihui/knitr/issues/1437).

**Comment by jennybc** [comment]
OK I'll close. If you learn anything useful about chunk options or other remedies, please let me know.

**Comment by JohnMount** [comment]
Looks like a chunk option https://github.com/rstudio/rmarkdown/issues/1150#event-1272182037

**Comment by jennybc** [comment]
Thanks for passing along.

I feel like that doesn't truly solve our problem. OK, yes, I can set that chunk option and force your example to give the output you wanted. But then **all** messages are being suppressed. It still doesn't provide a way to make `message()` work the same way interactively and inside something being knitted. Yes, we could set and unset `message = TRUE/FALSE` chunk-wise, but that's pretty goofy. Perhaps that is simply not possible with the way knitr and evaluate work.

``` r
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
print(paste('msg is:', msg))
#> [1] "msg is: hi"
message("but what about me?")
```

``` r
message("can you hear me now?")
#> can you hear me now?
```

**Comment by JohnMount** [comment]
I strongly agree, the `message=FALSE` control isn't a complete solution.

I had already been using the `message=FALSE` option a lot lately (so that status on long-running knitr jobs would be visible in real time in RStudio).  And I still did not anticipate that the `message=FALSE` control would be the one to deal with this issue, as it is way to broad to achieve the effect one would want.

Honestly I was using `reprex` to work on another issue on another package when I ran into this, and have already made the mistake of cross-filing to `knitr`/`rmarkdown`; so I am kind of "issued out" about now.

**Comment by jennybc** [comment]
> I had already been using the message=FALSE option a lot lately (so that status on long-running knitr jobs would be visible in real time in RStudio).

Aha! Well, that means we can do what you want another way. reprex can now capture stdout and stderr. So when you do `message = FALSE`, it will be diverted from the R process to the stdout/stderr of the render process. Here's a slight variant on our example that shows the previously "lost" message is being captured in stdout/stderr.

``` r
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
print(paste('msg is:', msg))
#> [1] "msg is: hi"
message("but what about me?")
```

``` r
message("can you hear me now?")
#> can you hear me now?
```

standard output and standard error

    #> but what about me?

---

Above was produced with 

```r
reprex({
  #+ message = FALSE
  msg <- utils::capture.output(
    {
      message("hi")
    },
    type='message')
  print(paste('msg is:', msg))
  message("but what about me?")
  
  #+ message = TRUE
  message("can you hear me now?")
}, std_out_err = TRUE)
```
