### ISSUE TITLE
Error when trying to capture test failure

### ISSUE THREAD

**Issue by sfirke** [tidyverse/reprex#119]
Trying to post a StackOverflow Q related to why this test fails:
```
my_fun <- function(x){
  if(x > 1){stop("my_fun() must be called on values of x less than or equal to 1")}
  x
}

library(testthat)
expect_error(my_fun(2),
             "my_fun() must be called on values of x less than or equal to 1")
```
I highlighted that above code, ran `reprex()`, and got:

> Error in readRDS(res) : error reading from connection

It succeeds when I've highlighted everything *but* the `expect_error` line above.  I'm running the current dev version of reprex, `0.1.1.9000 2017-09-29 Github (tidyverse/reprex@9a6fb4e)` - I upgraded in case the fix to #90 would solve this too, but looks like not for me.

**Comment by jennybc** [comment]
Smaller reprex 😂 of the problem with reprex. If I do this and expose traceback,

```r
reprex({
  my_fun <- function(x) {
    if (x > 1) stop("actual message")
    x
  }
  testthat::expect_error(my_fun(2), "wrong message")
})
```

I see this:

```
Rendering reprex...
 Error in readRDS(res) : error reading from connection 
5. readRDS(res) 
4. get_result(output = out, options) 
3. callr::r_safe(function(input) {
    rmarkdown::render(input, quiet = TRUE)
}, args = list(input = input), spinner = interactive() && !in_tests(), 
    stdout = std_out_err, stderr = std_out_err) at reprex.R#335
2. reprex_(r_file, std_file) at reprex.R#273
1. reprex({
    my_fun <- function(x) {
        if (x > 1) 
            stop("actual message") ... 
```

**Comment by jennybc** [comment]
You also cannot render an `.Rmd` with this code, even with `error = TRUE`. So we're seeing something about how knitr and testthat interact, that reprex faithfully inherits.

**Comment by jennybc** [comment]
I suspect it is connected to this: https://github.com/hadley/testthat/issues/460

**Comment by jennybc** [comment]
I think this is not a reprex issue *per se*, so am closing. If the knitr <--> testthat thing gets worked out, reprex would just become that much more useful.

**Comment by sfirke** [comment]
Everything here makes complete sense; thanks for looking into this! 👍

**Comment by jennybc** [comment]
Hmm, or maybe a better issue/PR to follow for this is https://github.com/hadley/testthat/pull/594
