### ISSUE TITLE
Elimintate <br/> when venue = 'so'

### ISSUE THREAD

**Issue by alistaire47** [tidyverse/reprex#133]
When `venue = 'so'`, a `<br/>` tag is inserted before the reprex, which results in useless space between preceding text and the reprex, e.g.

```r
reprex::reprex(letters, venue = 'so')
```
which writes the following to the clipboard:
```r
<!-- language-all: lang-r -->
<br/>

    letters
    #>  [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q"
    #> [18] "r" "s" "t" "u" "v" "w" "x" "y" "z"
```

Some digging showed the tag is coming from [whisker.R](https://github.com/tidyverse/reprex/blob/bbf829d46cd2e37d7d67de8f08799724fbb2fb5c/R/whisker.R), which contains

```r
fodder <- list(
  gh = list(
    yaml = yaml_gfm,
    si_start = "#'<details><summary>Session info</summary>",
    si_end = "#'</details>"
  ),
  so = list(
    yaml = yaml_md,
    so_syntax_highlighting = "#'<!-- language-all: lang-r --><br/>"
  ),
  r = list(
    yaml = yaml_gfm
  )
)
```
which `reprex::reprex` subsets with `fodder[[venue]]` ([line 261](https://github.com/tidyverse/reprex/blob/07d56cdd4b52612c641073cdf39b98172b80b285/R/reprex.R)).

Dropping `<br/>` should fix the issue. I'm happy to write a quick PR, if it's helpful.

**Comment by jennybc** [comment]
Everything looks fine on SO without this `<br/>`, then? Presumably it served some purpose at one point, but it's easy to believe that other changes have made this unnecessary.  PR is great or I can remove it.

**Comment by alistaire47** [comment]
Yep. I've got a PR ready, and in the course of assembling it, I discovered that without the `<br/>` it wouldn't put a newline after `<!-- language-all: lang-r -->`. That _does_ cause a problem on SO, so I added `\\n`, which fixes it.
