### ISSUE TITLE
reprex does not allow invalid whitespace?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/reprex#137]
This dataframe will not render properly in a reprex, the encoding is UTF-8, not "unknown"

![image](https://user-images.githubusercontent.com/7308115/33002802-0ac758c0-cd7c-11e7-86c8-5f0ca661a563.png)

which results in this reprex:

``` r
x <- tibble::tribble(
  ~id,                                                                                           ~value,
  390639,  "RATINGS: 4   MEAN: 3.83/5.0   WEIGHTED AVG: 3.39/5   IBU: 35   EST. CALORIES: 204   ABV: 6.8%",
  99472,                           "RATINGS: 89   WEIGHTED AVG: 3.64/5   EST. CALORIES: 188   ABV: 6.25%",
  361258,   "RATINGS: 8   MEAN: 3.7/5.0   WEIGHTED AVG: 3.45/5   IBU: 85   EST. CALORIES: 213   ABV: 7.1%"
)
#Returns UTF-8
Encoding(x$value)
#> [1] "unknown" "unknown" "unknown"
```

Is there a preferred way of sharing data like this? GitHub gists won't preserve this with the whitespace missing (indicated by the red space in RStudio).

**Comment by jennybc** [comment]
This seems related to an issue I opened on knitr: https://github.com/yihui/knitr/issues/1415. Is your issue about the incorrect reporting of encoding, i.e. the "unknown"'s? It seems so, i.e. the reprex looks ok. If so, then I think there's nothing I can do here in reprex, which essentially puts code into a template and submits to knitr.
