### ISSUE TITLE
Funky line break in the "ad"

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#140]
Why is this line break here? It is absent in the local html preview.

``` r
mean(rnorm(3))
#> [1] -0.4280615
```

Created on 2017-12-01 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
Yes it is a line break but it's not entirely funky.  It causes no trouble after `.md` -> `.html`. It is, however, a problem in a GitHub issue.

If I make a reprex with very long lines in prose comments, via `#'`, there are also hard line breaks. There's just seems to be something specifically unfortunate about a line break inside a markdown link that I might need to post-process away. Or use a pandoc option to prevent?

**Comment by jimhester** [comment]
Sorry for the spam, miss-clicked, I will send a PR to fix this, it has bugged me as well.
