### ISSUE TITLE
reprex does not show full package build output?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/reprex#141]
When trying to copy output from this command: `devtools::install_github("r-lib/pkgman")`, reprex will only render this:

``` r
devtools::install_github("r-lib/pkgman")
#> Warning in strptime(x, fmt, tz = "GMT"): unknown timezone 'zone/tz/2017c.
#> 1.0/zoneinfo/America/Chicago'
#> Downloading GitHub repo r-lib/pkgman@master
#> from URL https://api.github.com/repos/r-lib/pkgman/zipball/master
#> Installing pkgman
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/c9/4v_941557p15th5c9lkxnysr0000gn/T/RtmpukwSGy/devtools8c51210b942/r-lib-pkgman-ecc4396'  \
#>   --library='/Users/petergensler/Rlibs' --install-tests
#> 
#> Installation failed: Command failed (1)
```

when the full output is:

```
> devtools::install_github("r-lib/pkgman")
Downloading GitHub repo r-lib/pkgman@master
from URL https://api.github.com/repos/r-lib/pkgman/zipball/master
Installing pkgman
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/c9/4v_941557p15th5c9lkxnysr0000gn/T/Rtmpgkl2d1/devtools68e579eb5a4/r-lib-pkgman-ecc4396'  \
  --library='/Users/petergensler/Rlibs' --install-tests 

* installing *source* package ‘pkgman’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/Chicago'
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘rex’
ERROR: lazy loading failed for package ‘pkgman’
* removing ‘/Users/petergensler/Rlibs/pkgman’
Installation failed: Command failed (1)
```
session_info:
```

> devtools::session_info()
Session info ----------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-12-04                  

Packages --------------------------------------------------------
 package    * version    date       source                      
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)              
 backports    1.1.1      2017-09-25 CRAN (R 3.4.2)              
 base       * 3.4.2      2017-10-04 local                       
 callr        1.0.0.9000 2017-12-04 Github (r-lib/callr@550fa6b)
 clipr        0.4.0      2017-11-03 CRAN (R 3.4.2)              
 compiler     3.4.2      2017-10-04 local                       
 crayon       1.3.4      2017-09-16 CRAN (R 3.4.1)              
 curl         3.0        2017-10-06 CRAN (R 3.4.2)              
 datasets   * 3.4.2      2017-10-04 local                       
 debugme      1.1.0      2017-10-22 cran (@1.1.0)               
 devtools     1.13.4     2017-11-09 CRAN (R 3.4.2)              
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)              
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)              
 git2r        0.19.0     2017-07-19 CRAN (R 3.4.1)              
 graphics   * 3.4.2      2017-10-04 local                       
 grDevices  * 3.4.2      2017-10-04 local                       
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)              
 httr         1.3.1      2017-08-20 CRAN (R 3.4.1)              
 knitr        1.17       2017-08-10 CRAN (R 3.4.1)              
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)              
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)              
 methods    * 3.4.2      2017-10-04 local                       
 processx     2.0.0.1    2017-07-30 cran (@2.0.0.1)             
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)              
 Rcpp         0.12.14    2017-11-23 CRAN (R 3.4.3)              
 rmarkdown    1.8        2017-11-17 CRAN (R 3.4.2)              
 rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)              
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.1)              
 stats      * 3.4.2      2017-10-04 local                       
 stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)              
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)              
 tools        3.4.2      2017-10-04 local                       
 utils      * 3.4.2      2017-10-04 local                       
 whisker      0.3-2      2013-04-28 CRAN (R 3.4.0)              
 withr        2.1.0.9000 2017-12-04 Github (r-lib/withr@fe81c00)
 yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)   

```

Thoughts?

**Comment by batpigandme** [comment]
Created using 
```r
reprex::reprex(
          devtools::install_github("r-lib/pkgman"),
          std_out_err = TRUE))
```
``` r
devtools::install_github("r-lib/pkgman")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-lib/pkgman@master
#> from URL https://api.github.com/repos/r-lib/pkgman/zipball/master
#> Installing pkgman
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-lib/pkgdepends@master
#> from URL https://api.github.com/repos/r-lib/pkgdepends/zipball/master
#> Installing pkgdepends
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Installing curl
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a52a7fbfce/curl'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Installing lpSolve
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a55786c980/lpSolve'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Downloading GitHub repo r-lib/async@master
#> from URL https://api.github.com/repos/r-lib/async/zipball/master
#> Installing async
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5c9e6d21/r-lib-async-9a77e9b'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Downloading GitHub repo r-lib/desc@master
#> from URL https://api.github.com/repos/r-lib/desc/zipball/master
#> Installing desc
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5fbc9a5c/r-lib-desc-921eb35'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Downloading GitHub repo r-lib/filelock@master
#> from URL https://api.github.com/repos/r-lib/filelock/zipball/master
#> Installing filelock
#> Using GitHub PAT from envvar GITHUB_PAT
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5723cb0a5/r-lib-filelock-6e6b5df'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Downloading GitHub repo r-lib/pkgbuild@master
#> from URL https://api.github.com/repos/r-lib/pkgbuild/zipball/master
#> Installing pkgbuild
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-lib/callr@HEAD
#> from URL https://api.github.com/repos/r-lib/callr/zipball/HEAD
#> Installing callr
#> Downloading GitHub repo r-pkgs/processx@master
#> from URL https://api.github.com/repos/r-pkgs/processx/zipball/master
#> Installing processx
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a54be84035/r-lib-processx-ee98b68'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5399340e4/r-lib-callr-550fa6b'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5114acbca/r-lib-pkgbuild-ce7f6d1'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-lib/progress@master
#> from URL https://api.github.com/repos/r-lib/progress/zipball/master
#> Installing progress
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a561669f6b/r-lib-progress-3023c0b'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a52f1db0bf/r-lib-pkgdepends-8ed2a12'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-lib/pkginstall@master
#> from URL https://api.github.com/repos/r-lib/pkginstall/zipball/master
#> Installing pkginstall
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo tidyverse/rlang@master
#> from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
#> Installing rlang
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a560f65997/tidyverse-rlang-5ebcf24'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Downloading GitHub repo jimhester/archive@master
#> from URL https://api.github.com/repos/jimhester/archive/zipball/master
#> Installing archive
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo tidyverse/glue@master
#> from URL https://api.github.com/repos/tidyverse/glue/zipball/master
#> Installing glue
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a544101b6f/tidyverse-glue-69bc72c'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a529384b54/jimhester-archive-079351e'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Installation failed: Command failed (1)
#> Skipping install of 'glue' from a github remote, the SHA1 (69bc72ce) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a5e432b7a/r-lib-pkginstall-7f2b961'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Installation failed: Command failed (1)
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/xs/fdhsxg4x74xdwt8hjw27mb7w0000gn/T/RtmpR1K3H3/devtools95a56594cb93/r-lib-pkgman-75e3353'  \
#>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
#>   --install-tests
#> 
#> Installation failed: Command failed (1)
```

standard output and standard
    error

    #> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/curl_3.1.tgz'
    #> Content type 'application/x-gzip' length 403382 bytes (393 KB)
    #> ==================================================
    #> downloaded 393 KB
    #> 
    #> * installing *binary* package ‘curl’ ...
    #> * DONE (curl)
    #> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/lpSolve_5.6.13.tgz'
    #> Content type 'application/x-gzip' length 1024909 bytes (1000 KB)
    #> ==================================================
    #> downloaded 1000 KB
    #> 
    #> * installing *binary* package ‘lpSolve’ ...
    #> * DONE (lpSolve)
    #> * installing *source* package ‘async’ ...
    #> ** R
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (async)
    #> * installing *source* package ‘desc’ ...
    #> ** R
    #> ** inst
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (desc)
    #> * installing *source* package ‘filelock’ ...
    #> ** libs
    #> rm -f filelock.so init.o filelock-unix.o locklist.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c filelock-unix.c -o filelock-unix.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c locklist.c -o locklist.o
    #> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o filelock.so init.o filelock-unix.o locklist.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    #> installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/filelock/libs
    #> ** R
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (filelock)
    #> * installing *source* package ‘processx’ ...
    #> ** libs
    #> clang -Wall -g -O2  -Wall tools/px.c -o tools/px
    #> clang -Wall -g -O2  supervisor/supervisor.c supervisor/utils.c -o supervisor/supervisor
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c poll.c -o poll.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c processx-connection.c -o processx-connection.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c processx-vector.c -o processx-vector.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/childlist.c -o unix/childlist.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/connection.c -o unix/connection.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/processx.c -o unix/processx.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/sigchld.c -o unix/sigchld.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/utils.c -o unix/utils.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c unix/named_pipe.c -o unix/named_pipe.o
    #> clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c test-connections.cpp -o test-connections.o
    #> clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/testthat/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c test-runner.cpp -o test-runner.o
    #> clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o processx.so init.o poll.o processx-connection.o processx-vector.o unix/childlist.o unix/connection.o unix/processx.o unix/sigchld.o unix/utils.o unix/named_pipe.o test-connections.o test-runner.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    #> installing via 'install.libs.R' to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/processx
    #> ** R
    #> ** inst
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (processx)
    #> * installing *source* package ‘callr’ ...
    #> ** R
    #> ** inst
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (callr)
    #> * installing *source* package ‘pkgbuild’ ...
    #> ** R
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (pkgbuild)
    #> * installing *source* package ‘progress’ ...
    #> ** R
    #> ** inst
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (progress)
    #> * installing *source* package ‘pkgdepends’ ...
    #> ** R
    #> ** tests
    #> ** preparing package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** testing if installed package can be loaded
    #> * DONE (pkgdepends)
    #> * installing *source* package ‘rlang’ ...
    #> ** libs
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c arg.c -o arg.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c capture.c -o capture.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c dots.c -o dots.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c eval-tidy.c -o eval-tidy.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c exported-tests.c -o exported-tests.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c exported.c -o exported.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c expr-interp.c -o expr-interp.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c rlang.c -o rlang.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c utils.c -o utils.o
    #> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rlang.so arg.o capture.o dots.o eval-tidy.o exported-tests.o exported.o expr-interp.o init.o rlang.o utils.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    #> installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rlang/libs
    #> ** R
    #> ** tests
    #> ** byte-compile and prepare package for lazy loading
    #> ** help
    #> *** installing help indices
    #> *** copying figures
    #> ** building package indices
    #> ** installing vignettes
    #> ** testing if installed package can be loaded
    #> * DONE (rlang)
    #> * installing *source* package ‘glue’ ...
    #> ** libs
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c glue.c -o glue.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
    #> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c trim.c -o trim.o
    #> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o glue.so glue.o init.o trim.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    #> installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/glue/libs
    #> ** R
    #> ** tests
    #> ** byte-compile and prepare package for lazy loading
    #> ** help
    #> *** installing help indices
    #> ** building package indices
    #> ** installing vignettes
    #> ** testing if installed package can be loaded
    #> * DONE (glue)
    #> * installing *source* package ‘archive’ ...
    #> Package libarchive was not found in the pkg-config search path.
    #> Perhaps you should add the directory containing `libarchive.pc'
    #> to the PKG_CONFIG_PATH environment variable
    #> No package 'libarchive' found
    #> Package libarchive was not found in the pkg-config search path.
    #> Perhaps you should add the directory containing `libarchive.pc'
    #> to the PKG_CONFIG_PATH environment variable
    #> No package 'libarchive' found
    #> PKG_CFLAGS=
    #> PKG_LIBS=
    #> <stdin>:1:10: fatal error: 'archive.h' file not found
    #> #include <archive.h>
    #>          ^~~~~~~~~~~
    #> 1 error generated.
    #> ------------------------- ANTICONF ERROR ---------------------------
    #> Configuration failed because libarchive was not found. Try installing:
    #>  * deb: libarchive-dev (Debian, Ubuntu, etc)
    #>  * rpm: libarchive-devel (Fedora, CentOS, RHEL)
    #>  * csw: libarchive_dev (Solaris)
    #>  * brew: libarchive (Mac OSX)
    #> If libarchive is already installed, check that 'pkg-config' is in your
    #> PATH and PKG_CONFIG_PATH contains a libarchive.pc file. If pkg-config
    #> ERROR: configuration failed for package ‘archive’
    #> * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/archive’
    #> is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
    #> R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
    #> --------------------------------------------------------------------
    #> ERROR: dependency ‘archive’ is not available for package ‘pkginstall’
    #> * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pkginstall’
    #> ERROR: dependency ‘pkginstall’ is not available for package ‘pkgman’
    #> * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pkgman’

Created on 2017-12-14 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by pgensler** [comment]
Thanks.  I think it would help refine the roxygen to be less technical on what the argument does:

"Logical. This argument is meant to help include or not include output from terminal commands, such as building a package from source. Default is set to FALSE for no output."
