### ISSUE TITLE
About reprex loading issue.

### ISSUE THREAD

**Issue by Abhijitsj** [tidyverse/reprex#149]
I installed reprex as,
install.packages("reprex")
However, while loading i am getting beloww error.

library(reprex)
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning message:
package ‘reprex’ was built under R version 3.4.3 
Error: package or namespace load failed for ‘reprex’:
 unable to load R code in package ‘knitr’

**Comment by jennybc** [comment]
knitr has updated on CRAN in the past day or two so I wonder if that is somehow relevant. If you freshly install both reprex and knitr from CRAN and restart R, do you still have problems?
