### ISSUE TITLE
If clipboard not available, use `file.edit()`?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#151]
Inspired by https://github.com/tidyverse/reprex/issues/150

If we can't put the reprex on the user's clipboard (e.g. RStudio server), maybe we should go ahead and open the file for them? Or ask if they'd like that? Seems nicer than leaving people with a horrible temp file path and wishing them "good luck".

**Comment by jennybc** [comment]
@harrismcgehee Will you try this now? People using RStudio server, like you, should now get an offer to open the rendered result in an editor. Is this a better workflow?

**Comment by harrismcgehee** [comment]
Yes! It is already better!

However another suggestion: after rendering, the console is asking for input but the shiny app is still open so it might be confusing to users that they need to manually cancel or close the app before entering a selection in the console.

![image](https://user-images.githubusercontent.com/9814456/34677299-ad12ced6-f45d-11e7-8b49-e732dfff1363.png)

Can the app terminate but still accept input or can it ask for input another way?

**Comment by jennybc** [comment]
@harrismcgehee Will you open a new issue with this? I didn't even think about this interacting with the gadget.
