### ISSUE TITLE
issue producing reprex: could not find function "."

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/reprex#159]
Hi,

I am having trouble producing `reprex` for the following code. The code below works just fine, but when I run `reprex::reprex(input = "filename.R")` on the file in which this code is saved, it says it doesn't know what to do with `plyr::dlply`'s `.variables` argument. 

``` r

library(WRS2)

# read the csv file into a dataframe
df <- utils::read.csv(file = "C:/Users/Indrajeet Patil/Dropbox/Violence study - data/stimuli.csv")

# run robust anova for each measure
plyr::dlply(df, .(measure), function(data)
  WRS2::t1way(formula = rating ~ condition, data = data)
)
#> Error in .(measure): could not find function "."
```

Created on 2018-01-08 by the [reprex
                              package](http://reprex.tidyverse.org) (v0.1.1.9000).

Thanks.

**Comment by batpigandme** [comment]
Does it work if you load plyr at the beginning (as you've done with WRS2)?

Also, I don't think the actual data is relevant here, but, you've put in a path to your C-drive, which makes this example un-reproducible for anyone not on your computer. 

For future reference, try to either include a small sample of your data, or reproduce the problem using a built-in or scripted data frame. (Check out [reprex main requirements](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html#main-requirements) for some good tips on this).

**Comment by IndrajeetPatil** [comment]
Thanks! Explicitly loading `plyr` in the beginning solved the issue. 

P.S. Sorry, I thought the data was irrelevant so didn't use any of the inbuilt datasets. 

Here is an example with the solution implemented:
``` r
library(datasets)
data(iris)
library(plyr)
library(WRS2)

# run robust anova for each measure
plyr::dlply(iris, .(Species), function(data)
  WRS2::t1way(formula = Sepal.Length ~ Sepal.Width, data = data)
)
#> $setosa
#> Call:
#> WRS2::t1way(formula = Sepal.Length ~ Sepal.Width, data = data)
#> 
#> Test statistic: NA 
#> Degrees of Freedom 1: 15 
#> Degrees of Freedom 2: NA 
#> p-value: NA 
#> 
#> Explanatory measure of effect size: 1.08 
#> 
#> 
#> $versicolor
#> Call:
#> WRS2::t1way(formula = Sepal.Length ~ Sepal.Width, data = data)
#> 
#> Test statistic: NA 
#> Degrees of Freedom 1: 13 
#> Degrees of Freedom 2: NA 
#> p-value: NA 
#> 
#> Explanatory measure of effect size: 1.26 
#> 
#> 
#> $virginica
#> Call:
#> WRS2::t1way(formula = Sepal.Length ~ Sepal.Width, data = data)
#> 
#> Test statistic: NA 
#> Degrees of Freedom 1: 12 
#> Degrees of Freedom 2: NA 
#> p-value: NA 
#> 
#> Explanatory measure of effect size: 1.54 
#> 
#> 
#> attr(,"split_type")
#> [1] "data.frame"
#> attr(,"split_labels")
#>      Species
#> 1     setosa
#> 2 versicolor
#> 3  virginica
```

Created on 2018-01-08 by the [reprex
                              package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by batpigandme** [comment]
Looks good. No problem re. the data, just preaching reprex best-practices far and wide! 👍

I think the issue is that the `.`, as used, is itself a plyr function. So, without the package attached, you'll error out.
