### ISSUE TITLE
Shiny app blocks input when asking if user wants to open file for manual copying

### ISSUE THREAD

**Issue by harrismcgehee** [tidyverse/reprex#160]
After rendering, the console is asking for input but the shiny app is still open so it might be confusing to users that they need to manually close the app (cancelling does not dismiss the shiny app) before entering a selection in the console.

![image](https://user-images.githubusercontent.com/9814456/34677299-ad12ced6-f45d-11e7-8b49-e732dfff1363.png)

Can the app terminate but still accept input or can it ask for input another way?

**Comment by jennybc** [comment]
This is for the case when clipboard is unavailable, e.g. RStudio server.

**Comment by jennybc** [comment]
We now unconditionally open the rendered reprex in this situation, which should eliminate this problem.
