### ISSUE TITLE
Blank rendering in RStudio viewer on windows

### ISSUE THREAD

**Issue by cderv** [tidyverse/reprex#162]
In last dev version, the `reprex` is not rendered in RStudio Viewer, nor in the browser. When I dig into `tempdir()` folder where `reprex` file are created, the `md` is correct but the `html` is empty. Something seems off during rendering. 

No problem with last cran version. 
I will continue investigate the rendering part or try to find where it comes from with a `git bisect`. However, first you may have some info to point the search... Did you change something in the rendering process ? Do you know about this issue ? Do you have any idea ?

It happens with every reprex even the smaller like
``` r
print("a")
#> [1] "a"
```

it was created but I got no preview in the viewer and `file2450472a5e4c_reprex.html` that is generated is empty (0ko).

It may also come from conflict between `knitr` and `reprex` version ? don't know.

<details> 
<summary> session info </summary>

``` r
sessioninfo::session_info("reprex")
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.1 (2017-06-30)
#>  os       Windows 7 x64 SP 1          
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  French_France.1252          
#>  tz       Europe/Paris                
#>  date     2018-01-10                  
#> 
#> - Packages --------------------------------------------------------------
#>  package    * version    date       source                           
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.1)                   
#>  backports    1.1.1      2017-09-25 CRAN (R 3.4.1)                   
#>  base64enc    0.1-3      2015-07-28 CRAN (R 3.4.1)                   
#>  callr        1.0.0.9000 2018-01-10 Github (r-lib/callr@550fa6b)     
#>  clipr        0.4.0      2017-11-03 CRAN (R 3.4.2)                   
#>  crayon       1.3.4      2017-09-16 CRAN (R 3.4.2)                   
#>  debugme      1.0.2      2017-03-01 CRAN (R 3.4.1)                   
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.1)                   
#>  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                   
#>  highr        0.6        2016-05-09 CRAN (R 3.4.1)                   
#>  htmltools    0.3.6      2017-04-28 CRAN (R 3.4.1)                   
#>  jsonlite     1.5        2017-06-01 CRAN (R 3.4.1)                   
#>  knitr        1.17       2017-08-10 CRAN (R 3.4.1)                   
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.1)                   
#>  markdown     0.8        2017-04-20 CRAN (R 3.4.1)                   
#>  mime         0.5        2016-07-07 CRAN (R 3.4.1)                   
#>  processx     2.0.0.1    2017-07-30 CRAN (R 3.4.1)                   
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.1)                   
#>  Rcpp         0.12.14    2017-11-23 CRAN (R 3.4.2)                   
#>  reprex       0.1.1.9000 2018-01-10 Github (tidyverse/reprex@e3516a3)
#>  rlang        0.1.6      2017-12-21 CRAN (R 3.4.3)                   
#>  rmarkdown    1.8        2017-11-17 CRAN (R 3.4.2)                   
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.4.1)                   
#>  stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)                   
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.4.1)                   
#>  whisker      0.3-2      2013-04-28 CRAN (R 3.4.1)                   
#>  withr        2.1.1      2017-12-19 CRAN (R 3.4.3)                   
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.4.1)
```
Created on 2018-01-10 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

</details>

**Comment by batpigandme** [comment]
Hmm, that is odd. I just installed the latest dev reprex and 

``` r
print("a")
#> [1] "a"
```
Created on 2018-01-10 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

Which also shows up in the viewer:
![reprex in rstudio viewer](https://user-images.githubusercontent.com/831732/34780318-cf8f8faa-f5f0-11e7-94c1-e934f550387e.png)

That said, I'm on a Mac, so it could be OS-specific (just adding some more data to the mix).

**Comment by jennybc** [comment]
@cderv I think I have seen this on my Windows VM recently. And it's specific to when `outfile` is unspecified, i.e. I think `outfile = NA` or `outfile= "foo"` both produce a normal html preview. Suggests it's something around the temp file (path).

**Comment by cderv** [comment]
I can confirm that `outfile = NA` works. Thanks ! 

I will see what I can do to make a PR. It is a bit annoying that default behaviour `outfile=NULL` does not work on windows...

**Comment by jennybc** [comment]
It definitely used to work, so I am optimistic this is not a terribly tricky thing to sort out. Thanks in advance for any light you can shed!

**Comment by cderv** [comment]
Issue seems to be in `force_tempdir`

```r
force_tempdir <- function(x) {
  if (identical(normalizePath(tempdir()), dirname(normalizePath(x)))) {
    return(x)
  }
  tmp_file <- file.path(tempdir(), basename(x))
  file.copy(x, tmp_file, overwrite = TRUE)
  tmp_file
}
```

Maybe this is only on windows but it should be this to worl
```r
force_tempdir <- function(x) {
  if (identical(normalizePath(tempdir()), normalizePath(dirname(x)))) {
    return(x)
  }
  tmp_file <- file.path(tempdir(), basename(x))
  file.copy(x, tmp_file, overwrite = TRUE)
  tmp_file
}
```

`dirname` on `normalizePath` changes the `\\` in `/` so identical is FALSE so file is copied with rong path and without success (hence 0ko files). I just change the order : `normalizePath` on `dirname`

What do you think ? I prefer to ask before a PR. (per `CONTRIBUTING.md`)

**Comment by jennybc** [comment]
Looks good! I'd love a PR.
