### ISSUE TITLE
Optionally run reprex() as if the R session were interactive.

### ISSUE THREAD

**Issue by wlandau** [tidyverse/reprex#167]
Some code behaves differently in interactive vs non-interactive R sessions. Example: [random ggplot2 tips on startup](https://github.com/tidyverse/ggplot2/blob/bf9255e50cb8333e26133cc81927e5baff986d2a/R/zzz.r#L2). A discussion is [here](https://community.rstudio.com/t/set-seed-ggplot2-and-reprex/4346).

Current behavior:

```r
reprex::reprex(x = interactive())
## FALSE
```

Desired behavior:

```r
reprex::reprex(x = interactive(), interactive = FALSE) # still default
## FALSE
reprex::reprex(x = interactive(), interactive = TRUE)
## TRUE
```

**Comment by wlandau** [comment]
Also, apologies for mangling the title when I first submitted the issue.

**Comment by jennybc** [comment]
There's a variety of reason internally why this won't be possible. Maybe there is some way to make this work, but I think it would be trouble.
