### ISSUE TITLE
Getting failed to upload file error when reprex contains a plot

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/reprex#168]
Reprex figures have been failing to upload, I thought it had to do with a specific reprex I [ran earlier](https://github.com/tidyverse/ggplot2/issues/2402#issuecomment-359245430), but that doesn't seem to be the case. True both with and without using the addin, but with addin, getting an error executing the Addin

![image](https://user-images.githubusercontent.com/831732/35198949-93c9bd06-fec4-11e7-850e-9a4f792e2f48.png)

``` r
reprex::reprex({
  library(tidyverse)
  mtcars %>%
    group_by(cyl) %>%
    mutate(rank = min_rank(desc(mpg))) %>%
    ggplot(aes(mpg, rank)) +
    geom_point() +
    theme_classic()
})
#> Rendering reprex...
#> Error in (opts_knit$get("upload.fun"))(x): failed to upload file49f52fba920_reprex_files/figure-markdown_strict/reprex-body-1.png
```
Created on 2018-01-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

There is no error executing addin if the reprex doesn't contain a chart:
``` r
library(tidyverse)
mtcars %>%
  group_by(cyl) %>%
  mutate(rank = min_rank(desc(mpg)))
#> # A tibble: 32 x 12
#> # Groups: cyl [3]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb  rank
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <int>
#>  1  21.0  6.00   160 110    3.90  2.62  16.5  0     1.00  4.00  4.00     2
#>  2  21.0  6.00   160 110    3.90  2.88  17.0  0     1.00  4.00  4.00     2
#>  3  22.8  4.00   108  93.0  3.85  2.32  18.6  1.00  1.00  4.00  1.00     8
#>  4  21.4  6.00   258 110    3.08  3.22  19.4  1.00  0     3.00  1.00     1
#>  5  18.7  8.00   360 175    3.15  3.44  17.0  0     0     3.00  2.00     2
#>  6  18.1  6.00   225 105    2.76  3.46  20.2  1.00  0     3.00  1.00     6
#>  7  14.3  8.00   360 245    3.21  3.57  15.8  0     0     3.00  4.00    11
#>  8  24.4  4.00   147  62.0  3.69  3.19  20.0  1.00  0     4.00  2.00     7
#>  9  22.8  4.00   141  95.0  3.92  3.15  22.9  1.00  0     4.00  2.00     8
#> 10  19.2  6.00   168 123    3.92  3.44  18.3  1.00  0     4.00  4.00     5
#> # ... with 22 more rows
```
Created on 2018-01-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

[_n.b._ I will look more closely at this later on, I just didn't want to lose track of the prob while I work on other things]

**Comment by jennybc** [comment]
It's a problem with `knitr::imgur_upload()`, not reprex itself. Perhaps the imgur client ID built-into knitr has stopped working? I'll check that.

``` r
f = tempfile(fileext = '.png')
png(f); plot(rnorm(100), main = R.version.string); dev.off()
#> quartz_off_screen 
#>                 2
res = knitr::imgur_upload(f)
#> Error in knitr::imgur_upload(f): failed to upload /var/folders/vr/gzrbtprx6ybg85y5pvwm1ct40000gn/T//Rtmp3irMlj/file160520953d3f.png
```

Created on 2018-01-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
No, it's a different reason. The upload is actually happening but the data sent back seems to have changed. I will make a PR to knitr.

**Comment by jennybc** [comment]
https://github.com/yihui/knitr/pull/1496

**Comment by jennybc** [comment]
After that change to knitr, we appear to be back in business.

``` r
plot(rnorm(100), main = R.version.string)
```

![](https://i.imgur.com/ZCOnlAh.png)

Created on 2018-01-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
I think the correct solution, though, may be for reprex to provide it's own upload function. At least for the very-soon CRAN release.

**Comment by batpigandme** [comment]
Ugh, I'm still getting the error, but everything works fine when I run it on RSP. I think for some reason [rsam](https://github.com/yonicd/rsam) (RStudio Addin Manager) messed things up for me with addins. But, reprex and knitr are working as they should in all other env'ts.

**Comment by batpigandme** [comment]
Well, time machine + your patch has me up and running again!

**Comment by yihui** [comment]
I'm hoping to make a CRAN release of knitr before rstudio::conf, but I don't feel very optimistic about it (it may take CRAN maintainers several days to process it).

**Comment by jennybc** [comment]
I've always wondered if you @yihui wanted me to be using a reprex-specific client ID anyway. Do you?

**Comment by yihui** [comment]
No. I don't care. The only reason you may want a different ID is the rate limit, but I guess it should be unlikely to hit the limit. I'm not aware of other packages using this functions.

**Comment by GillesSanMartin** [comment]
Hello

I have the exact same problem even after installing the last github version of knitr and also outside RStudio

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=fr_BE.UTF-8       LC_NUMERIC=C               LC_TIME=fr_BE.UTF-8       
 [4] LC_COLLATE=fr_BE.UTF-8     LC_MONETARY=fr_BE.UTF-8    LC_MESSAGES=fr_BE.UTF-8   
 [7] LC_PAPER=fr_BE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.19.4 reprex_0.2.0

loaded via a namespace (and not attached):
 [1] digest_0.6.15    crayon_1.3.4     withr_2.1.1.9000 assertthat_0.2.0 R6_2.2.2         git2r_0.18.0    
 [7] httr_1.3.1       rlang_0.1.6.9003 debugme_1.1.0    curl_3.0         rstudioapi_0.7   callr_2.0.2     
[13] whisker_0.3-2    devtools_1.13.2  tools_3.4.3      compiler_3.4.3   clipr_0.4.0      memoise_1.1.0 
```

**Comment by jennybc** [comment]
What happens when you try to use knitr's imgur upload function w/o using reprex?

```
f = tempfile(fileext = '.png')
png(f); plot(rnorm(100), main = R.version.string); dev.off()
res = knitr::imgur_upload(f)
```

**Comment by GillesSanMartin** [comment]
I have an error : 
```r
Error in knitr::imgur_upload(f) : 
  failed to upload /tmp/RtmpirXB0t/file1e8d57ba847a.png
```

**Comment by jennybc** [comment]
What happens if you re-install knitr from CRAN (which is at version 1.19 vs. the version 1.19.4 that you show)?

If that clears it up, then you should probably take this over to knitr.

**Comment by GillesSanMartin** [comment]
I still have an error : 
```r
Error in knitr::imgur_upload(f) : 
  failed to upload /tmp/RtmpprkThD/file24103134d973.png
```
I have opened an issue on [knitr](https://github.com/yihui/knitr/issues/1514)

**Comment by yihui** [comment]
I'm sure it was due to a breaking change in xml2: https://github.com/r-lib/xml2/releases/tag/v1.2.0 and the solution is "When in doubt, upgrade": https://yihui.name/en/2017/05/when-in-doubt-upgrade/

**Comment by GillesSanMartin** [comment]
I can confirm this was the problem. Sorry again for wasting your time !

**Comment by yihui** [comment]
No worries!

**Comment by pschloss** [comment]
I'm getting this after updating xml2 and knitr. 

```
> reprex()
Rendering reprex...
Error in (opts_knit$get("upload.fun"))(x) : 
  failed to upload fileb35754aa4d5c_reprex_files/figure-markdown_strict/reprex-body-1.png
```

Following @jennybc's test code above gives...

```
Error in knitr::imgur_upload(f) : 
  failed to upload /var/folders/8p/j4r5_4yn7jg5z3s6p_ky8lc40000gn/T//Rtmpxu1IOO/fileb3571d9e917e.png
```

Here's what I've got in my R...

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.2.0      stringr_1.2.0      dplyr_0.7.4        purrr_0.2.4       
[5] readr_1.1.1        tidyr_0.8.0        tibble_1.4.2       ggplot2_2.2.1.9000
[9] tidyverse_1.2.1   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     cellranger_1.1.0 pillar_1.1.0     compiler_3.4.3  
 [5] plyr_1.8.4       bindr_0.1        tools_3.4.3      lubridate_1.7.2 
 [9] jsonlite_1.5     nlme_3.1-131     gtable_0.2.0     lattice_0.20-35 
[13] pkgconfig_2.0.1  rlang_0.2.0.9001 psych_1.7.5      cli_1.0.0       
[17] rstudioapi_0.7   parallel_3.4.3   haven_1.1.0      bindrcpp_0.2    
[21] withr_2.1.2      xml2_1.1.1       httr_1.3.1       hms_0.3         
[25] grid_3.4.3       glue_1.2.0       R6_2.2.2         readxl_1.0.0    
[29] foreign_0.8-69   modelr_0.1.1     reshape2_1.4.3   magrittr_1.5    
[33] scales_0.5.0     rvest_0.3.2      assertthat_0.2.0 mnormt_1.5-5    
[37] colorspace_1.3-2 stringi_1.1.6    lazyeval_0.2.1   munsell_0.4.3   
[41] broom_0.4.3      crayon_1.3.4    
```

**Comment by yihui** [comment]
@pschloss Repeat myself above https://github.com/tidyverse/reprex/issues/168#issuecomment-367027374: When in doubt, upgrade.

Or `devtools::install_github('yihui/knitr')`

**Comment by pschloss** [comment]
Evidently, should be "When in doubt uninstall, reinstall. Multiple times". Thanks
