### ISSUE TITLE
Error in (opts_knit$get("upload.fun"))(x)

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/reprex#170]
Below is the completely reproducible code. If I try to create a `reprex` for this code, it gives me the following error-
`Rendering reprex...
Error in (opts_knit$get("upload.fun"))(x) : 
  failed to upload file100c2bd4528_reprex_files/figure-markdown_strict/reprex-body-1.png`

Why is it not working? 

Code:
```
# loading the libraries
library(ggplot2)
library(grid)
library(cowplot)

# preparing the data
dat = data.frame(x = rnorm(100),
                 y = rexp(100),
                 grp = factor(sample(1:2, 100, replace = TRUE)))

# preparing the plot
plot <- ggplot(dat, aes(x = x, y = y, color = grp)) +
  geom_point() + 
  facet_wrap( ~ grp) +
  theme(panel.spacing = unit(2, "lines"))

# preparing the line
gline <- grid::linesGrob(x = 0.5)
cowplot::ggdraw(gline)

# plotting both the plot and the line
cowplot::ggdraw() +
  cowplot::draw_plot(plot) +
  cowplot::draw_plot(gline) 


```

**Comment by jennybc** [comment]
The imgur API behaviour recently changed. I just made [a fix in knitr](https://github.com/yihui/knitr/pull/1496) to accommodate this (which is where this functionality comes from). So if you install knitr from GitHub, you should be back in business.

``` r
devtools::install_github("yihui/knitr")
```

**Comment by IndrajeetPatil** [comment]
It worked! Thanks.

**Comment by cderv** [comment]
@jennybc I think the fix you made could come from `xml2` 📦 changes of behaviour and not from imgur that changes its content. There is a [breaking change](https://github.com/r-lib/xml2/blob/master/NEWS.md#breaking-changes) with the `as_list` function. knitr may know need `xml2 (>= 1.2.0)`.

**Comment by jennybc** [comment]
@cderv OK thanks, I've re-opened so I remember to check this. Your hypothesis sounds very plausible.

**Comment by jennybc** [comment]
Thanks @cderv for following up in knitr itself.
