### ISSUE TITLE
Add GIF of `reprex` process with expressions to `README`

### ISSUE THREAD

**Issue by coatless** [tidyverse/reprex#172]
Instead of having a stagnant screenshot of the end of the process, would it be possible to include a GIF that captures _how_ the **reprex** is being constructed? 

As an example, I recently made the following reprex to demo to my course:

![reprex_demo](https://user-images.githubusercontent.com/833642/35532158-ee89ceb2-04fe-11e8-9531-eef12b275e2e.gif)

**Comment by jennybc** [comment]
Sure, I'd be happy to have such a GIF! 

There are several in this contributed article:
http://reprex.tidyverse.org/articles/articles/magic-reprex.html

Not sure if any is ideal for these purposes, though.

Are you @coatless game to propose and/or make one? I think @batpigandme is also good to consult re: making or discussing requirements for the minimal GIF.

**Comment by coatless** [comment]
Tool-wise, I can only make GIFs with [GIPHY Capture](https://itunes.apple.com/us/app/giphy-capture-the-gif-maker/id668208984?mt=12). If the intent is to focus on the copy and paste portion that Nick did, I won't be able to overlay the shortcut `[Cmd/Cntrl + C]` and then `[Cmd/Cntrl + V]` after running the _R_ command.  So, @batpigandme and her GIF magic would come into play.

Content-wise, for the GIF, I think the best approach would be fewer more common lines of code to appeal to as large a base as possible. For the initial GIF, I opted for an arithmetic example, whose error was rather glaring due to the omission of `y`:

```r
# install.packages("devtools")
# devtools::install_github("tidyverse/reprex")
library(reprex)

reprex({
  x = 1 + 2
  y + x
})
```

However, it may make more sense to construct a better example based on the dos and donts: 

http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

Thoughts?

**Comment by batpigandme** [comment]
I can definitely help with shortcut overlay, and (if for that reason alone) I think we should do it with a light-background colour, as you have, @coatless. Heading to rstudio::conf today, but I'm happy to cook up a few examples so we can look at some options. (Perfect in-flight activity for someone who is skeptical of using unsecured Fly-Fi).

**Comment by jennybc** [comment]
What's the current thinking about this? Still seems like it would be good to have a very short well-crafted GIF.

**Comment by batpigandme** [comment]
Can do. I'll use an example from the slides with library, objects, and reprex expression, unless there's something specific you're envisioning.

**Comment by jennybc** [comment]
Thanks @batpigandme. I'll be happy to use what you provide.

Perhaps we could scheme or even just do this together next week?

**Comment by batpigandme** [comment]
Sounds good!

**Comment by jennybc** [comment]
I'm pretty content with the video in this blog post:

https://www.tidyverse.org/blog/2021/02/reprex-1-0-0/

and other articles we've gained over the year also feature some helpful videos/gifs. Going to close since I have no more immediate, concrete plans.
