### ISSUE TITLE
reprex did not save highcharter plot correctly

### ISSUE THREAD

**Issue by tungmilan** [tidyverse/reprex#185]
reprex only captured one part of the plot when plotting with `highcharter` package 

**Expected output**

![rplot01](https://user-images.githubusercontent.com/6590141/37365862-f7b467d4-26bb-11e8-83e6-0c5b87a30a88.png)

**Code**
``` r
library(magrittr)
library(highcharter)

data("citytemp")

highchart() %>% 
  hc_title(text = "This is a <sup>Sup</sup>title I will display &#8738;", useHTML = TRUE) %>% 
  hc_subtitle(text = "This is a <sub>sub</sub>title", useHTML = TRUE) %>% 
  hc_xAxis(categories = citytemp$month) %>% 
  hc_xAxis(title = list(text = "hola<sub>subtag</sub>", useHTML = TRUE)) %>%
  hc_yAxis(title = list(text = "Temperature (?C)"),
           max = 35) %>%
  
  hc_legend(useHTML = TRUE) %>% 
  hc_tooltip(useHTML = TRUE, shared = TRUE) %>% 
  
  hc_add_series(name = "hey! im a X<sup>2</sup> wich &#8712 to real <b>R</b><sup>+</sup>", 
                data = citytemp$tokyo) %>% 
  hc_add_series(name = "look! an integral &#8755", data = citytemp$london)
```

![](https://i.imgur.com/mglAg15.png)

Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
I believe this is related to the way that highcharter works. If you look at the gif, below, you'll see that the series ~rolls out as an animation.
![https://i.imgur.com/HnPwFkQ.gif](https://i.imgur.com/HnPwFkQ.gif)

**Comment by batpigandme** [comment]
reprex captures the entire chart, otherwise you wouldn't have the entire axis, title, and legend at the bottom. The difference is that reprex captures it only part-way through the animation.

**Comment by batpigandme** [comment]
Yeah, @tungmilan, highcharter is an htmlwidget, which I don't believe reprex is supporting at this time (see @jennybc 's comment here: https://github.com/tidyverse/reprex/issues/78#issuecomment-290924480 ).

**Comment by tungmilan** [comment]
Thanks @batpigandme !
