### ISSUE TITLE
FR: Enable capture of RStudio API output.

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/reprex#186]
Might not be worth it/out of scope, but just realized `rstudioapi::` funs can't be reprexed while trying to help someone on community.

``` r
rstudioapi::getThemeInfo()
#> Error: RStudio not running

rstudioapi::getSourceEditorContext()
#> Error: RStudio not running

rstudioapi::versionInfo()
#> Error: RStudio not running
```
Created on 2018-03-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jennybc** [comment]
This is basically how rstudioapi is meant to work, i.e. to be inert if you are not in an interactive RStudio session. And reprex is meant to force your code to run in a fresh R process. So I will have to look into whether this is even possible.

**Comment by batpigandme** [comment]
Priority level: **extremely** low! Especially since there's really no downside to copying and pasting output in those scenarios.

**Comment by jennybc** [comment]
I think this one remains a non-starter.
