### ISSUE TITLE
Prevent `reprex()` from successfully running if it is not a reprex

### ISSUE THREAD

**Issue by prosoitos** [tidyverse/reprex#191]
Thought inspired by [conversation on this thread](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219/13).

The purpose of the package `reprex` seems a little unclear to me:

- is it to render code for sharing (as suggested by the main package description: "Render bits of R code for sharing")?
- is it to render reprexes for sharing (as suggested by the package name and the sentence: "What is a reprex? It’s a reproducible example, as coined by Romain Francois.")?

Since `reprex` does more than just rendering bits of R code (it also runs that code in a fresh environment and gives helpful error messages if the code is not a reprex) and with such a name, I think the intent is more likely to be the later.

If the purpose is to produce nicely formatted reprexes, I wonder whether it is a good idea to have `reprex()` output nicely formatted reprex-looking chunks that are not reprexes when run on non-reprexes. Admittedly, those do have an error message. But that message seems to be ignored by some new R users who think that they are posting reprexes, for instance on the [RStudio Community site](https://community.rstudio.com/).

This also has the effect of blurring the concept of reprex with the idea of formatted code.

The tidyverse functions are often more strict than their base R counterparts: they will not run but will give an error message when there are data type inconsistencies for instance (while the base R functions would give an output, for better or for worse). I really like this behaviour. I like the idea of functions not running if fed inadequate code. I was wondering if having `reprex()` *only* output the error message (and not a reprex-looking chunk) when run on a non-reprex might not make the package more inline with this philosophy as well as making the actual concept of reprex much more clear to new R users?

Then one could safely say "`reprex()` outputs a reprex", which is not always the case now. And asking people to use the package `reprex` would necessarily mean to make a reprex in the first place (since without a reprex, the code would not run but just give an error message). People would never post what they think is a reprex when it isn't. It might make helping them easier, but mostly, it might be more pedagogical about the actual concept of reprex (which seems to be surrounded by a fair amount of confusion amongst people new to R).

**Comment by jennybc** [comment]
I don't think I quite follow. Can you show an example of "now" vs. what you are proposing? Or sketch the change you propose?

**Comment by prosoitos** [comment]
Sure. Sorry for not being more clear.

I feel that the package `reprex` as it is now might be contributing to some confusion between `reprex` (the package, the function, or the output of the function) and a reprex (reproducible example).

I find the current behaviour to be consistant with the stated package description, both on GitHub ("Render bits of R code for sharing") and in the help file ("Description Convenience wrapper that uses the 'rmarkdown' package to render small snippets of code to target formats that include both code and output.").

But if the package goal is only to render code and output, then its name is misleading: rendering  formatted code is in itself independent from the concept of reprex.

This is a problem because a lot of users view it, not as a formatting/copy-paste convenience tool but as a tool to create reprexes (and obviously this is why it was created). But of course the package does not magically turn code into reproducible examples. You have to feed reprexes to it to get (formatted and "pastable") reprexes out of it.

Basically, non-reprex in, non-reprex out.

[This blog](https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/) for instance, which is used in the [RStudio Community FAQ on reprex](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219/2) highlights this confusion: it really sounds like you install the package, copy some code, run `reprex::reprex()` and tada!, "Everything that you need to post a reprex is now automatically stored on your clipboard!" But of course, that is not true if your code was not a reprex.

And even the function output on the console is "Rendered reprex is on the clipboard." (even if the rendered output is not a reprex at all).

If reprex as taken by this console output or this blog author means the output of the function `reprex()`, that works. But calling "reprex" something whether it is or not a reprex (= reproducing example) is confusing and problematic.

And this, unsurprisingly, leads to posts on the RStudio Community where people say that they are posting a reprex when they are not because, for instance, they are loading local data to which we don't have access.

To make all of this a lot simpler and clean all those semantic confusions which lead to (I think) real concepts confusions, I suggest that the goal of the package be to create redered reprexes (as the name really suggests), rather than rendered code. When fed a reprex, `reprex()` would behave as it does now (and output a rendered reprex as promised). But when fed a non-reprex, instead of still telling you that "Rendered reprex is on the clipboard." and outputting a nicely formatted code that can be happily pasted in a forum (with, true, an error at the bottom of it), the function could simply output that error message in the console but not successfully do all the other things. No rendered anything. Nothing to paste. The error message could be informative of course so that the new R user is not left hanging ("This is not a reprex. Are you sure you bla bla bla" for instance).

This way, one could simply say that `reprex()` outputs reprexes. "Rendered reprex is on the clipboard." would only appear when it is indeed a reprex that is on the clipboard. When telling new R users to post a reprex, it would be clear that we actually mean, well, a reprex. Not just the output of `reprex()` that is called reprex even when it is not a reprex.

**Comment by prosoitos** [comment]
Note: if the ability to "render bits of R code", independently of whether they are reprexes or not, were deemed useful (and I think it could be), then there could simply be another function (for instance `reprex::render()`) which would behave as `reprex::reprex(show = F)` does now, with the only difference that the console output would be "Rendered *code* is on the clipboard."

That way, if someone wants to output a rendered version of something that is not a reprex, that capability is not lost, but without creating any confusion around the concept of reproducible example and without potential semantic non-sense.

**Comment by hadley** [comment]
`reprex()` already goes to considerable lengths to ensure the code is reproducible (e.g.. running in a clean session and in temporary directory). Of course, the user can always work around this.  But there is no way to tell if code is fully reproducible or not. (Because sometimes generating an error is the whole point of the reprex)

I think you are trying to solve a human communication problem with code.

**Comment by prosoitos** [comment]
> (e.g.. running in a clean session and in temporary directory)

Totally! and the package is phenomenal for that!

So, what about outputting an error message in the console (and no viewer or paste capabilities) when the code contains a path? Maybe it would give too many false positives? Loading local data seems to be the most common situation where people produce `reprex()` outputs which are not reprexes.

**Comment by prosoitos** [comment]
Or, if false positives are a concern, at least a warning in the console of the kind "Your code contains a path. Are you sure that it will run on another machine?" with a "Y/n" dialog, so that the user could just answer "Y" and get an output if they know what they are doing, or if they really want to output regardless of the fact that it is not a reprex. It would give people who are not aware of the local data issue a pause and they would probably realize what they are not doing right.

**Comment by jennybc** [comment]
I agree with @hadley that we've arrived at the frontier between the technical constraints that reprex can provide and human issues.

I have legitimate uses for reprex that read from a file. For example, sometimes people aren't at liberty to share an Excel file with me, but they can still use reprex to show me some puzzle they are having with readxl.

Beyond that, parsing the code and deciding whether it reads from a path or not is not a trivial ask. Ditto for parsing results and judging if the error is "legitimate" or "invalid". reprex just dumps user's code into a templated `.R` file and renders it. It does no analysis of the code or its results.

We're planning a short video (or 2 or 3) to help those who'd rather see reprex in that form. I'll make sure to hit some of these classic gotchas, the same way I did in the rOpenSci Community Call [such as slide 10](https://speakerdeck.com/jennybc/reprex-help-me-help-you?slide=10).

**Comment by prosoitos** [comment]
OK. Thank you for the time given to my suggestion! and thank you for the extra resources to help new users.

**Comment by jennybc** [comment]
Another thing to keep on the radar is the eventual possibility of suggesting that people run their reprex on   http://cloud.rstudio.com. The combination of that and the reprex package would reinforce all possible aspects of "self-contained". But we're not there yet.
