### ISSUE TITLE
Feature request: venue = "jira"

### ISSUE THREAD

**Issue by karawoo** [tidyverse/reprex#193]
Would it be possible for reprex to support Jira's idiosyncratic markup format?

```r
reprex({plot(1:10)}, venue = "jira")
```

would yield:

```
{code:r}
plot(1:10)
{code}

!https://i.imgur.com/dsy8tx3.png!
```

**Comment by jennybc** [comment]
From Googling, this doesn't look very easy. But if someone wanted to tackle it, I'd be happy to discuss.

**Comment by jennybc** [comment]
@karawoo Do you still care about this? If so, can you re-Google the situation and see if generating markup for Jira has gotten any easier since we last checked? I think the answer is probably "no" and we should just close this.

**Comment by karawoo** [comment]
They've been slowly rolling out more markdown support, it's not 100% yet but I think we can just close.

**Comment by cderv** [comment]
I am interested about this one as we use Jira.
If jira is compatible with R highlight ', this seems as easy as `{code: r}`. 
If note the syntax should be added based on 
 https://gist.github.com/yihui/1804862

Anyway I think this could be added without drawbacks.
