### ISSUE TITLE
Make the ad optional?

### ISSUE THREAD

**Issue by zx8754** [tidyverse/reprex#196]
There are now over [600 Q&As](https://stackoverflow.com/search?q=%5Br%5D+%22by+the+reprex+package%22) on StackOverflow that has the ad in it.  I find it irrelevant to the StackOverflow Q&A, maybe add an option not to add the ad in the output? 

```r
reprex(mean(rnorm(3)), ad = FALSE)
```
Related to #69

**Comment by jennybc** [comment]
There is already an argument and option to control this. In fact, I'm surprised your code doesn't suppress the ad?

For me, both of these call suppress the ad:

``` r
## full name of `advertise` argument
reprex(mean(rnorm(3)), advertise = FALSE)

## rely on partial match
reprex(mean(rnorm(3)), ad = FALSE)
```

The `advertise` argument is additionally under the control of an option, as documented here:

<https://reprex.tidyverse.org/reference/opt.html>

You can use code like that shown there:

``` r
options(
  reprex.advertise = FALSE,
)
```

in `.Rprofile` to change the behaviour of `reprex::reprex()` universally.

I too am ambivalent about the ad, but am also tired of terribly formatted reprexes, so feel like more people should use reprex. We debated what the default should be but ended up deciding to use `TRUE`.
