### ISSUE TITLE
Reprex erroring about multi-line string being invalid R code

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/reprex#206]
Trying to run this code throws an error (I added `#` because it would malrender the code on GitHub otherwise): 
```r
# reprex::reprex({
# "
# ```{r, eval = FALSE}
# ```
# "
# })

# Error: First three lines of putative code are:
# "
# ```{r, eval = FALSE}
# ```
# which isn't valid R code.
# Are we going in circles? Did you just run reprex()?
# In that case, the clipboard now holds the *rendered* result.
```

I know this is an edge-case use case but I needed it because I use a function that takes R markdown code as input. 

I also tried 
```r
# reprex::reprex({"```{r, eval = FALSE}
#  ```"})
```

Which runs but gives a strange output.
![screen shot 2018-09-14 at 11 59 06](https://user-images.githubusercontent.com/10477073/45543738-99dcab80-b815-11e8-8381-baf7e60b8845.png)

Putting the string on one line gives the expected output but I need multi-line input.

**Comment by batpigandme** [comment]
I think this is the same as for 
https://github.com/tidyverse/reprex/issues/202

**Comment by jennybc** [comment]
@batpigandme No, this is different. My crude check for people trying to reprex the output of reprex is getting triggered. I knew this day would come.

**Comment by jennybc** [comment]
@lorenzwalthert What exactly are you trying to do? And can you express it in any way that no line matches this regex `"^```"`?

**Comment by jennybc** [comment]
Well ... maybe it is both #202 and the `ensure_not_dogfood()` check. Because if I disable that check, then I get the same error as #202, which is a knitr/rmarkdown problem.

**Comment by jennybc** [comment]
OK I made it possible to reprex such code, if you really want to, in an interactive session. But now you're going to run into the knitr problem described in https://github.com/rstudio/rmarkdown/issues/1444, which is being worked on.
