### ISSUE TITLE
Make style = TRUE the default?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/reprex#208]
This might make the life of package maintainers a tad easier. Two things to remember:

- _styler_ throws an unhelpful error message if the code can't be parsed, we might want to do better to help users.
- Only `scope = "line_breaks"` guarantees that the input is identical to the output as far as the parser is concerned. This will keep `=` for assignment and won't add `()` after function calls in pipes but is the safer alternative.

CC @lorenzwalthert.

**Comment by lorenzwalthert** [comment]
There's been a debate about whether to use `style = TRUE` as a default in #108. Personally, I think it would make sense, but there is also an easy way to make `reprex` calls behaving as if `style = TRUE` was the default, which I use: Just use the global option to *change the default* of the argument: 
```r
options(reprex.style = TRUE)
```
The thing is probably that most users don't do that or know how to do it.

**Comment by batpigandme** [comment]
FWIW, I think (depending on how different an individual's coding style is from styler) this could be kind of confusing to the unsuspecting user.

**Comment by krlmlr** [comment]
Ah, that's what the `opt()` does ;-)

_reprex_ could talk about it, like: 

> Code formatted by styler. To turn off, set options(reprex.style) = FALSE.

Keeping this open, because the original discussion is now a year old and _styler_ has matured a lot since then.

**Comment by jennybc** [comment]
Maybe `style` should default to `NA`, with default logic of: set `style = TRUE` if styler is installed.

This would need to be implemented and is also connected to centralized documentation for options: #259

**Comment by lorenzwalthert** [comment]
I know this is for interactive use primarily but isn't it generally considered bad practice to have code behaving differently depending on what other packages are installed? Do you plan to have similar behavior for other options?

**Comment by jennybc** [comment]
Well, there is precedent for this sort of thing for a worklow / interactive package. For example, httr and everything which depends on it uses a local web server for auth (vs out-of-bound auth) depending on whether httpuv is installed.

I don't think it's a big deal either way.

But we can also leave `style = FALSE` as the default.
