### ISSUE TITLE
reprex appears to be producing quoted output that isn't legible/usable

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/reprex#209]
The following code block produces overly quoted non-legible/not-executable output.

```r
packageVersion("reprex")
# [1] ‘0.2.1’
reprex::reprex('
library("ggplot2")
packageVersion("reprex")
packageVersion("ggplot2")

d <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))

# produces 2 bars when we expect 3
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(-1e-2, 1 + 1e-2))
# one warning
# Warning message:
#   Removed 1 rows containing missing values (geom_bar).
')
```

Output left in clipboard on macOS R version 3.5.0 (2018-04-23).

``` r
"\nlibrary(\"ggplot2\")\npackageVersion(\"reprex\")\npackageVersion(\"ggplot2\")\n\nd <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))\n\n# produces 2 bars when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-2, 1 + 1e-2))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n"
#> [1] "\nlibrary(\"ggplot2\")\npackageVersion(\"reprex\")\npackageVersion(\"ggplot2\")\n\nd <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))\n\n# produces 2 bars when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-2, 1 + 1e-2))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n"
```

<sup>Created on 2018-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
The first argument of `reprex()` is `x`, which is an unquoted expression, e.g. `reprex(rnorm(3))`.

The above looks like you want to provide quoted text as input, which means you should use the `input` argument. It works like so:

> Character. If has length one and lacks a terminating newline, interpreted as the path to a file containing reprex code. Otherwise, assumed to hold reprex code as character vector.

which means you would need to turn your input into a character *vector* (vs. one long string).

Finally, given that you've got that code somewhere, the easiest way to input is probably via clipboard or by saving it to a named file and providing that path to `input`.

At one point, I contemplated taking input like you give via `input`, but it's very hard to handle embedded newlines properly. I decided it was more robust to force the user to give a character vector or to use clipboard/file.

**Comment by jennybc** [comment]
If I copy the code to the clipboard and do `reprex()` or write it to "foo.R" and do `reprex(input = "foo.R")`, I see:

``` r
library("ggplot2")
packageVersion("reprex")
#> [1] '0.2.1'
packageVersion("ggplot2")
#> [1] '3.0.0'

d <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))

# produces 2 bars when we expect 3
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(-1e-2, 1 + 1e-2))
#> Warning: Removed 1 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/q6e5cZa.png)

<sup>Created on 2018-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by JohnMount** [comment]
Thanks.  I think the following had been my workflow and I just forgot the curly braces:

```r
reprex::reprex({
library("ggplot2")
packageVersion("reprex")
packageVersion("ggplot2")

d <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))

# produces 2 bars when we expect 3
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(-1e-2, 1 + 1e-2))
# one warning
# Warning message:
#   Removed 1 rows containing missing values (geom_bar).
})
```
t

**Comment by jennybc** [comment]
Yeah, makes sense.
