### ISSUE TITLE
reprex erroring in RStudio preview

### ISSUE THREAD

**Issue by alistaire47** [tidyverse/reprex#212]
In the current RStudio preview builds (I'm currently on 1.2.1047, though the previous one was the same), calling `reprex` on anything returns an error:

```r
reprex::reprex(2 + 2)
#> Rendering reprex...
#> Error in eval(substitute(expr), data, enclos = parent.frame()) : 
#>   is.character(repos) is not TRUE
```
It doesn't seem to matter how input is passed; it all errors out.

Running the exact same code from the command line (via [rtichoke](https://github.com/randy3k/rtichoke)) works fine:

```r
reprex::reprex(2 + 2)
#> Rendering reprex...
#> Rendered reprex is on the clipboard.

cat(clipr::read_clip(), sep = "\n")
#> ``` r
#> 2 + 2
#> #> [1] 4
#> ```
```

If this bug report belongs on the RStudio side, let me know, but as far as I've seen, this only happens with reprex. I'm using the current GitHub version of reprex.

**Comment by jennybc** [comment]
This smells like a buglet in callr. But it's also not immediately clear to me why this matters or what would be different re: RStudio vs rtichoke.

My `repos` option is a character vector. Is yours a list?

``` r
str(getOption("repos"))
#>  Named chr [1:2] "https://cran.rstudio.org" ...
#>  - attr(*, "names")= chr [1:2] "CRAN" "CRAN"
```

<sup>Created on 2018-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
cc @gaborcsardi

**Comment by jennybc** [comment]
So ... is the IDE making `repos` into a list? Is that a new thing? I understand that callr needs to cope with that. But if the IDE is doing that ... maybe it should not?

**Comment by alistaire47** [comment]
> My `repos` option is a character vector. Is yours a list?
> 
> ```r
> str(getOption("repos"))
> #>  Named chr [1:2] "https://cran.rstudio.org" ...
> #>  - attr(*, "names")= chr [1:2] "CRAN" "CRAN"
> ```

Oh, I didn't realize this was an option. Mine is a list:

```r
> str(getOption("repos"))
List of 1
 $ CRAN: chr "https://cran.rstudio.com/"
 - attr(*, "RStudio")= logi TRUE
```
...though I didn't explicitly set it with `option` (maybe I did through a GUI window at some point?), so I'm not really sure where that value came from. Setting it to a character vector does resolve the problem:
````r
> options(repos = c(CRAN = "https://cran.rstudio.com/"))
> reprex::reprex(2 + 2) 
Rendering reprex...
Rendered reprex is on the clipboard.
> cat(clipr::read_clip(), sep = "\n")
``` r
2 + 2
#> [1] 4
```
````
Should I close this, or leave it open in case someone else needs the workaround?

**Comment by jennybc** [comment]
Please leave it open. I feel like your observation about behaviour in RStudio vs rtichoke may contain some useful information.

**Comment by yutannihilation** [comment]
> I'm not really sure where that value came from.

RStudio does set `repos` option if you don't set it in your `~/.Rprofile`. The codes are around here: https://github.com/rstudio/rstudio/blob/a07815d2eca1435ee4032b1dad2a47211db28fd4/src/cpp/r/R/Tools.R#L536-L545.

It seems it became a `list` when RStudio supported a secondary repo URL.

https://github.com/rstudio/rstudio/commit/a07815d2eca1435ee4032b1dad2a47211db28fd4#diff-3ff32c696ec8d43c82f9fb507864c200R519

As a temporal workaround until callr is updated, you can specify `repos` in your `~/.Rprofile`. For example:

```r
local({
  r <- getOption("repos")
  r["CRAN"] <- "https://cran.rstudio.com/"
  options(repos = r)
})
```

**Comment by jennybc** [comment]
Thanks all. The IDE team is aware of this and has already gone back to character vector:

https://github.com/rstudio/rstudio/commit/1d7e3466cc70416c68dca93a363811e222a4acfe

So the workaround is to set the `repos` option in `.Rprofile` (which I always do anyway). And in the long-term, RStudio will go back to making this a list.

**Comment by jennybc** [comment]
Also https://github.com/rstudio/rstudio/issues/3669

**Comment by yutannihilation** [comment]
Oh, sorry, I didn't notice that. Thanks!
