### ISSUE TITLE
reprex makes me jump to my web browser on Windows (again?)

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/reprex#213]
related: https://github.com/rstudio/rstudio/issues/3577#issuecomment-426360720

On Windows, I am jumped to browsers every time I execute `reprex()`. Once I've fixed this problem (https://github.com/tidyverse/reprex/pull/75), but it seems to occur again (I don't remember when). Now I slightly suspect https://github.com/tidyverse/reprex/pull/164 is involved.

Ultimately this is an RStudio's bug, but they say it won't get fixed for v1.2, so it'd be better to have suggested workaround in reprex package, though it seems only few people get affected. Hopefully, I'll send a PR for this if I have some time...

**Comment by jennybc** [comment]
All path handling has been fs-ified since #164 happened.

I read through 
https://github.com/rstudio/rstudio/issues/3577#issuecomment-426360720.

Are you willing to explore the effects of processing file path with various functions from fs? And how they interact with the behaviour of `viewer()` in RStudio? I'm talking about `fs:path_expand()`, `fs::path::real()` and friends. Let me know if there's a function that produces a path that RStudio recognizes as below the temp directory.

I would test myself in my Windows VM, but my username doesn't trigger this short path name ickiness.

**Comment by jennybc** [comment]
Try installing from this branch and let me know what happens:

https://github.com/tidyverse/reprex/tree/path-real

**Comment by jennybc** [comment]
Actually, now that I re-read the RStudio issue, I have done the opposite of what's needed in that branch. I don't think it will help you. The workaround is pretty yucky ... but I guess I could try it.

**Comment by yutannihilation** [comment]
Thanks for the infomation! I don't know how fs treats Windows' tricky 8.3 filename. But, I think I'll have to explore it...

**Comment by jennybc** [comment]
I think the best way to use @kevinushey's proposed workaround might be to write a wrapper around `viewer()` and put that in your `.Rprofile`. Because this problem won't be limited to reprex anyway.

**Comment by yutannihilation** [comment]
Hmm... OK, it sounds reasonable. I'll do so. Should I close this then?

**Comment by jennybc** [comment]
If you get it to work, it wold be great to post your solution here, in case there are other people in the unlucky intersection sets you find yourself in. But you could do that after closing it, just as well as before.

**Comment by yutannihilation** [comment]
Thanks, this worked for me :)

``` r
local({
  options(viewer = function(url, height = NULL){
    # If `url` is a URL, no tweak is needed
    if (grepl("^(https?|ftps?)://", url))
      return(rstudioapi::viewer(url))

    # If `url` is a path, tweak the path
    path <- normalizePath(url)
    tmpdir <- normalizePath(tempdir())
    if (regexpr(tmpdir, path, fixed = TRUE) == 1)
      path <- sub(tmpdir, tempdir(), path, fixed = TRUE)

    rstudioapi::viewer(path)
  })
})
```

**Comment by jennybc** [comment]
Awesome! Glad it's working for you and appreciate you sharing the solution.
