### ISSUE TITLE
suggestion: data obscurator

### ISSUE THREAD

**Issue by r2evans** [tidyverse/reprex#216]
For discussion: what are your thoughts on the value of an "obscuration" function? Frequently I see (and have experienced as an asker) the pain of questions that cannot show actual data, whether due to PII/HIPPA, IP, company rules, etc. Occasionally the asker will be savvy enough to concoct some fake data, either programmatically or by other means. Those without the skills, however, are left asking unsubstantiated questions (fielding requests for reproducibility, perhaps being closed for "no data, no code").

"Anonymizing" the data (similar to survey data) is not always sufficient, since the numbers or categories themselves might be indicative of the type of data (if hiding that is important to the asker). Hashing/ciphering the text is also not good, as patterns might develop. The point is to be irreversible.

I suggest some simple (and at times, ugly) functions that would turn something like:

```r
indata
# # A tibble: 2 x 7
#   ssn         lname address               phone        lgl     int   num
#   <chr>       <chr> <chr>                 <chr>        <lgl> <dbl> <dbl>
# 1 123-45-6789 Smith 123 Main St           504-586-1928 TRUE     73  3.14
# 2 234-56-7890 Doe   1600 Pennsylvania Ave 201-293-2222 FALSE     2 -2.72
obscure(indata)
# # A tibble: 2 x 7
#   ssn         lname address          phone        lgl     int   num
#   <chr>       <chr> <chr>            <chr>        <lgl> <dbl> <dbl>
# 1 10481096150 QiKhO ys4E043Cvzop7HJz 847219001755 FALSE    44  1.93
# 2 0668611-981 lgXH  ApF  t  fJIF     252481--3425 TRUE     55  1.52
obscure(indata)
# # A tibble: 2 x 7
#   ssn         lname address               phone        lgl     int   num
#   <chr>       <chr> <chr>                 <chr>        <lgl> <dbl> <dbl>
# 1 94222967-70 dFslG zn E4FIf2z87g D UDNeX 25-14124-615 FALSE    12 0.166
# 2 269-06-1-00 sRo   iMXdFv4ybWH           585213-63935 TRUE      9 0.209
obscure(indata)
# # A tibble: 2 x 7
#   ssn         lname address               phone        lgl     int   num
#   <chr>       <chr> <chr>                 <chr>        <lgl> <dbl> <dbl>
# 1 208-26973-0 UxZN  xCf frm7I2L           5713-1311-62 FALSE    23 -2.37
# 2 97508067889 tSLB  xLn86dsY3 S cBzloU8Gi 57292--45895 TRUE     68 -2.42
```

The individual filters can be smarter in order to keep some patterns ... perhaps looking for U.S. SSNs and several patterns of US and international phone numbers, but I don't think much effort is strictly needed here.

I'd think `reprex` is a great place for functionality like this: as the use of it (for me, mostly seen on SO) grows, it is becoming easier to suggest to new users "use `reprex` to improve this question"; even better if problems with data privacy can be addressed in the same place.

**Comment by jennybc** [comment]
I'm afraid this is beyond the scope of reprex, so  I'm closing this issue.

I'm asking in rOpenSci slack for suggestions ... because I think there are some existing package that could help with this. I'll come back and comment or maybe someone will just do so directly.

**Comment by nfultz** [comment]
See also https://github.com/DeclareDesign/fabricatr and wakefield - https://github.com/trinker/wakefield

**Comment by karawoo** [comment]
charlatan is another option too: https://github.com/ropensci/charlatan
