### ISSUE TITLE
Error: `highlight` command line tool doesn't appear to be installed. Therefore, `venue = "rtf"` is not supported.

### ISSUE THREAD

**Issue by aegerton** [tidyverse/reprex#217]
When running the script below, the following error message is encountered;-

```
Error: `highlight` command line tool doesn't appear to be installed.
Therefore, `venue = "rtf"` is not supported.
```

If other venue options are used (e.g. "r", or "so"), the script executes perfectly.

How do I fix this, please?

``` r
library(reprex)
reprex(
  mean(rnorm(100)),
  venue = "rtf"
)
#> Error: `highlight` command line tool doesn't appear to be installed.
#> Therefore, `venue = "rtf"` is not supported.
```

<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
Since this is a documented, I'm going to close the issue. @cderv is right on, you need the highlight CLT. ✔️
