### ISSUE TITLE
Reprex from selection does not work when selection is in new window

### ISSUE THREAD

**Issue by blairj09** [tidyverse/reprex#222]
This may be an IDE issue. When "Reprex selection" is run from the Addins menu and the selected R code exists in an external RStudio window an R code execution error is thrown. The following error message is shown in the console:

```
Error in x[[n]] : 
  attempt to select less than one element in integerOneIndex
```

**Comment by jennybc** [comment]
Hmm... I think this might be an IDE issue or at least a question for them. If I run the "Reprex selection" adding from my keyboard shortcut, it works for a selection in a popped out window. But if I try to use it from the Addins menu, I get the same error as you.

Thoughts @kevinushey?

**Comment by kevinushey** [comment]
This is more because when you click the Addins menu in the main window, that window gets focused and so RStudio thinks it should use the selection associated with that window. I think we need to add an Addins menu button to satellite windows as well to help handle this.

**Comment by jennybc** [comment]
So, shall I close this as something that's not really a matter for reprex and its addin to sort out @kevinushey? That seems correct to me.

**Comment by kevinushey** [comment]
Yes please -- @blairj09, if you have time, could you re-file this issue at https://github.com/rstudio/rstudio/issues?
