### ISSUE TITLE
reprex cannot work with C:\Users\name.surname\AppData\Local\Temp

### ISSUE THREAD

**Issue by cstepper** [tidyverse/reprex#223]
Rendering reprex fails when the Temp directory root contains a . , 
e.g. _C:\Users\name.surname\AppData\Local\Temp_ in Windows.

In subfunction make_filenames(), when creating the list with the filenames, the 
function from fs-package fs::path_ext_set() results is a filebase like
_C:\Users\name_
Consequently, the list with files, e.g. the r_file, contains names like 
_C:\Users\name.R_

When there is no permission to write in the C:\users\ directory, the reprex() fails.

---
```r
reprex::reprex()
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file 'C:/Users/christoph.R': Permission denied
```

**Comment by jennybc** [comment]
Thanks, I've reported it in fs, where it seems the fix should happen.
