### ISSUE TITLE
Entrace base errors?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/reprex#230]
This is a follow-up to #229 and how dev rlang always shows a backtrace on error in non-interactive sessions. It might be helpful and more consistent to entrace base errors with `rlang::entrace()`. Unfortunately, simply setting `options(error = rlang::entrace)` doesn't work because `rmarkdown::render()` captures the errors before `entrace()` has a chance to be called.

Would it be worth it to find a solution to that problem? The easiest way might be to add an option to entrace errors in rmarkdown itself.

**Comment by hadley** [comment]
We should also provide some optional way to activate this for warnings too.

**Comment by lionel-** [comment]
`options(warn = 2)` should work. But won't that create misleading reprexes if we enable it by default?

**Comment by lionel-** [comment]
Or should we capture all warnings, with an accompanying trace?

**Comment by lionel-** [comment]
https://github.com/r-lib/rlang/issues/714

**Comment by jennybc** [comment]
@lionel- Has the world changed since we last discussed this? What's the best way to support entrancing base errors?

**Comment by lionel-** [comment]
Adding `cnd_entrace` as a calling handler. That's also the correct way to entrace rlang errors. Cf the weird dplyr example I've just posted in the other thread.
