### ISSUE TITLE
argument or option to automatically open file that holds rendered reprex

### ISSUE THREAD

**Issue by dskard** [tidyverse/reprex#235]
Please briefly describe your problem and what output you expect. If
you have a question, please don't use this form. Instead, ask on
<https://community.rstudio.com/> or <https://stackoverflow.com/>.

---

Brief description of the problem

When I create a reprex on rstudio.cloud, I am always reminded that the reprex package cannot save my markdown for me in the clipboard and I am prompted to answer a question about opening the output file for manual copy:

```r
library(reprex)
reprex(y <- x)
#> Rendering reprex...
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
#> Unable to put result on the clipboard. How to get it:
#>   * Capture what `reprex()` returns.
#>   * Consult the output file. Control via `outfile` argument.
#> Path to `outfile`:
#>   * /tmp/RtmpiFZNg0/reprexc323d3fbd9/reprex_reprex.md
#> Open the output file for manual copy?
#> 1: yes
#> 2: no
#> 
#> Selection: 1
```

I would like to bypass the yes/no question asking if i want to open the output file for manual copy, by setting a function option. In the example below, I propose a new logical function option, named `show_markdown`, that will:
1. automatically open the output file for manual copy when set to TRUE
2. skip opening the output file for manual copy when set to FALSE
3. prompt the user to open the output file for manual copy when set to NULL, NA, or any non-logical type.

Scenario 1: automatically open the output file for manual copy
```r
library(reprex)
reprex(y <- x, show_markdown=TRUE)
#> Rendering reprex...
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
#> Unable to put result on the clipboard. How to get it:
#>   * Capture what `reprex()` returns.
#>   * Consult the output file. Control via `outfile` argument.
#> Path to `outfile`:
#>   * /tmp/RtmpiFZNg0/reprexc323d3fbd9/reprex_reprex.md
```
Window with markdown should be displayed to user.

Scenario 2: skip opening the output file for manual copy
```r
library(reprex)
reprex(y <- x, show_markdown=FALSE)
#> Rendering reprex...
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
#> Unable to put result on the clipboard. How to get it:
#>   * Capture what `reprex()` returns.
#>   * Consult the output file. Control via `outfile` argument.
#> Path to `outfile`:
#>   * /tmp/RtmpiFZNg0/reprexc323d3fbd9/reprex_reprex.md
```
Window with markdown should not be displayed to user. Probably most useful when combined with setting the `outfile` option so the name of the output file is predictable.

Scenario 3: (default scenario) prompt the user to open the output file for manual copy
```r
library(reprex)
reprex(y <- x, show_markdown=NULL)
#> Rendering reprex...
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
#> Unable to put result on the clipboard. How to get it:
#>   * Capture what `reprex()` returns.
#>   * Consult the output file. Control via `outfile` argument.
#> Path to `outfile`:
#>   * /tmp/RtmpiFZNg0/reprexc323d3fbd9/reprex_reprex.md
#> Open the output file for manual copy?
#> 1: yes
#> 2: no
#> 
#> Selection: 1
```
User will select 1 or 2 to determine whether a window with markdown should not be displayed.

**Comment by jennybc** [comment]
This is related to PR #163 "Adapt reprex_addin to be more useful when the clipboard isn't available". Should be tackled together.

**Comment by dikiprawisuda** [comment]
Excuse, is there an update to this? How do we use the function to bypass the yes/no question asking if i want to open the output file for manual copy?
I want to automate my time-consuming analysis followed by `save.data()` and then `fun::shutdown(wait=600)` function, and currently having a hard time to figure out how to report an error should there is any. I have checked `sink()` and `savehistory()`, and nothing seemed to do what I wanted.

Thank you.
Best,

**Comment by jennybc** [comment]
@dikiprawisuda I'm not entirely sure how your question is connected to this thread. That is, I understand that you would use the hypothetical `show_markdown` argument proposed by @dskard. But then you lose me when you start talking about `save.image()`, `fun::shutdown(wait=600)`, and `savehistory()`. I suspect you might be trying to use this package for something it's not built for.

**Comment by jennybc** [comment]
Also: I should be able to detect usage in Cloud and RSP and be proactive about how I make the output available, regardless of the specific ways I make this smoother.

**Comment by jennybc** [comment]
I do now unconditionally open (and "select all") the rendered reprex file. Hopefully this makes reprex life much nicer on RSP and Cloud.
