### ISSUE TITLE
`venue = roxygen`?

### ISSUE THREAD

**Issue by HughParsonage** [tidyverse/reprex#243]
I'd like to propose another option for `venue`: roxygen.

This feature would make writing `@examples` a bit easier. In particular it would avoid having to prefix the code with `#'` for the code part and `#' #>` for the output, reduce accidental commits of syntactically (or otherwise) incorrect examples, and make it easier to identify dependencies.

On the last point, it may be appropriate to assume that when `venue = 'rox'` and one is working within a package directory that the package source in the current directory is attached. (So that `library(<mypackage>)` is not necessary in the rendered output.)

I can make a PR if you'd like. I searched for roxygen in the issues list but only found references to current behaviour, not feature requests refused.

**Comment by IndrajeetPatil** [comment]
This might be of interest to you:
https://github.com/csgillespie/roxygen2Comment

**Comment by jennybc** [comment]
I identify with the need to format examples in roxygen comments (indent, really). But am not convinced it's best addressed in reprex.

In RStudio, you can easily walk through your examples. The only friction I feel is around whitespace. This feels more like the domain of styler (or RStudio IDE).

What do you have in mind for the roxygen venue?

**Comment by jennybc** [comment]
I remain unsure of the goal here.

For now, it feels like these tools provide the example-wrangling support I need:

  * If I need to add `#' ` to many lines of code (i.e. convert a code snippet to roxygen syntax), I use multiple cursors in RStudio.
  * I execute examples via Cmd + Enter in RStudio.
  * styler now offers support applying code style to examples <https://styler.r-lib.org>

I'm sure other non-RStudio IDEs offer multiple cursors and, perhaps, example execution. So I don't see an obvious gap for reprex to fill.
