### ISSUE TITLE
checking for non-deterministic output

### ISSUE THREAD

**Issue by franknarf1** [tidyverse/reprex#245]
I noticed a [reprex-created chunk on SO](https://stackoverflow.com/q/55148371) and was surprised that it was not reproducible -- `rbinom` is used but there's no `set.seed` before it.

A crude pseudo fix would be to have reprex compile its output twice and test equality, warning the user on failure.

Omitting `set.seed` seems like a pretty common user error when it comes to making reprexes and it would be nice to catch, so hopefully addressing it is in scope. I noticed that no-repro-because-local-file is out of scope https://github.com/tidyverse/reprex/issues/191#issuecomment-389348964 but I guess the fix there is a lot tougher (...run the code in a virtual machine or something).

**Comment by jennybc** [comment]
I would classify this as another "won't fix", I'm afraid. I think it's also in the art/human part of making a reprex vs. the mechanical part reprex targets. We have nothing here that ingests the reprex output and doing so isn't trivial. What if someone has a reprex that reveals current time, for example? That would also change each time it's run, but does that invalidate the reprex? I don't know. Or "it depends". So that's why I am loath to get into the business of vetting the output.

We do already urge people to use `set.seed()` here FWIW:
https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

**Comment by franknarf1** [comment]
That makes sense. Thanks, Jenny.

For anyone interested in a helper function, here's what I came up with:

```` r
library(reprex)
#> Warning: package 'reprex' was built under R version 3.5.3
library(diffobj)
#> Warning: package 'diffobj' was built under R version 3.5.3

f = function(x){
  expr = substitute({
    reprex(x, show = FALSE)
    readClipboard()
  })

  ok <- identical(r1 <- eval(expr), suppressMessages(r2 <- eval(expr)))
  
  if (!ok){ 
    message("Diffs between two runs of the code are shown.")
    print(diffPrint(r1, r2))
  }

  return(invisible(r1))
}

f(1+2)
#> Rendering reprex...
#> Rendered reprex is on the clipboard.

f(sample(10))
#> Rendering reprex...
#> Rendered reprex is on the clipboard.
#> Diffs between two runs of the code are shown.
#> < r1                                                                       
#> > r2                                                                       
#> @@ 1,5 / 1,5 @@                                                            
#>   [1] "``` r"                                                              
#>                                                                            
#>   [2] "sample(10)"                                                         
#>                                                                            
#> < [3] "#>  [1]  9  4  5 10  2  6  7  3  8  1"                              
#> :                                                                          
#> > [3] "#>  [1]  3  7  5  4 10  1  6  2  9  8"                              
#> :                                                                          
#>   [4] "```"                                                                
#>                                                                            
#>   [5] ""                                                                   
#> 
````

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

(Getting meta by trying out `reprex()` here on my clipboard. `diffPrint` opens results in my browser, where the diff is more obvious, rather than the console as shown here.)

This is probably overkill relative to the "human communication" Hadley mentioned in the link of "set the seed" or "read the dos and don'ts" (that you linked).
