### ISSUE TITLE
include reticulate Python information when appropriate?

### ISSUE THREAD

**Issue by kevinushey** [tidyverse/reprex#246]
A feature request: If we were able to detect that an example was using the `reticulate` package, e.g. as with [here](https://github.com/rstudio/reticulate/issues/454), it would be helpful if `reprex` could also print out the Python session info as well -- e.g. probably just the output of `reticulate::py_config()`.

**Comment by jennybc** [comment]
How would you propose to detect reticulate usage?

**Comment by kevinushey** [comment]
I think something like the following would work -- after running the reprex, this could be run to check whether `reticulate` was loaded + Python was activated:

```r
reticulateLoaded <-
  "reticulate" %in% loadedNamespaces() &&
  reticulate::py_available(initialize = FALSE)

if (reticulateLoaded)
  print(reticulate::py_config())
```

Not sure if there's a clean way to inject 'post-reprex' code into the bit of code that the user has asked to be run, though.

**Comment by jennybc** [comment]
> Not sure if there's a clean way to inject 'post-reprex' code into the bit of code that the user has asked to be run, though.

Yes, I think this can be handled in the template.

**Comment by jennybc** [comment]
Closing in favour of https://github.com/r-lib/sessioninfo/issues/33
