### ISSUE TITLE
Create snippet or extend addin to allow specification of LANGUAGE for the reprex

### ISSUE THREAD

**Issue by andresrcs** [tidyverse/reprex#250]
My native language is spanish, so the locale on my PC is ES_us, but when posting a reprex to English forums that includes error messages I would like to use EN_us, that way I wouldn't have to manually translate the error messages, or remeber to manually change my locale beforehand, would you consider adding this funtionality? I think it would be pretty handy for non-English users.

**Comment by batpigandme** [comment]
Temporary workaround – you can use the withr package [`with_envvar()`](http://withr.r-lib.org/reference/with_envvar.html) to set the language.
So, for example, if I run the following code as a reprex as I usually do, the message is in English.
``` r
dplyr::select(foo)
#> Error in dplyr::select(foo): object 'foo' not found
```
If I run:
```r
withr::with_envvar(c("LANG" = "de_DE.UTF-8"), code = {reprex::reprex(dplyr::select(foo))})
```
I get
``` r
dplyr::select(foo)
#> Error in dplyr::select(foo): Objekt 'foo' nicht gefunden
```

<sup>Created on 2019-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by andresrcs** [comment]
Thanks Mara!, this is a nice walkaround solution although I still think it would be more convenient to have this functionality on the `reprex()` function itself.

**Comment by jennybc** [comment]
Assuming that one attached reprex in `.Rprofile` (I think heavy users do) and that target code is on the clipboard, @batpigandme's suggestion gets very slick:

``` r
withr::with_envvar(
  c("LANG" = "de_DE.UTF-8"),
  reprex()
)
```

I can't see a built-in solution being that much easier/shorter and it would create more code to document and maintain. This looks like a good thing to create an RStudio snippet for? Or maybe even incorporate this as a feature in the current gadget/addin? I think all of those are better ways to make this withr trick more available than to add another argument to `reprex()` itself.

Do you @andresrcs have any interest in noodling on those alternatives?

**Comment by jennybc** [comment]
Re: tidyverse dev day

An interesting project would be to explore exposing this method of setting the locale in the existing addin/gadget.

reprex already imports withr. A minimum viable product, therefore, it's adding some sort of input for locale and reworking the `reprex()` call if the user uses a non-default locale. I don't have much experience with doing this in general, so I would anticipate some thought around ... what are the best ways to change locale? does the user have to type all of this out or is there some sort of dropdown menu? etc etc.

**Comment by andresrcs** [comment]
> Do you @andresrcs have any interest in noodling on those alternatives?

I whish I had the skills needed, I just ended up creating my own `reprex_en()` variant in `.Rprofile`, this is more convenient for me since I mostly work on RStudio Server, so no clipboard available.

```
reprex_en <- function(...) {
  withr::with_envvar(
    c("LANG" = "en_US.UTF-8"),
    reprex::reprex(...)
  )
}
```

**Comment by jennybc** [comment]
I think that's a good solution! Esp. for an individual.

I will leave this open in case anyone want to tackle at our next tidyverse dev day.

**Comment by andresrcs** [comment]
Maybe something like this would be more generalizable 
```
reprex_locale <- function(..., locale = "en_US.UTF-8") {
  withr::with_envvar(
    c("LANG" = locale),
    reprex::reprex(...)
  )
}
```

**Comment by jennybc** [comment]
This is *related* to locale in the `Sys.getlocale()` sense. But, from those docs, note that:

> Note that the LANGUAGE environment variable has precedence over "LC_MESSAGES" in selecting the language for message translation on most R platforms.

And this thread appears to really be about this, more than true aspects of locale. Not sure what to make of this difference: "LANGUAGE" (from the docs) vs. "LANG" (from all the working examples here).

**Comment by hadley** [comment]
Details at https://cran.rstudio.com/doc/manuals/r-devel/R-admin.html#Localization-of-messages — I think setting `LANGUAGE` is most appropriate here

**Comment by andresrcs** [comment]
This make me think about this other use case, being English the "lingua franca" I also want my labels in English when rendering a reprex.

``` r
reprex_locale <- function(..., locale = "en_US.UTF-8") {
    withr::with_envvar(
        c("LC_ALL" = locale),
        reprex::reprex(...)
    )
}

library(ggplot2)
df <- data.frame(stringsAsFactors = FALSE,
                 date = as.Date(c("2019-01-01", "2019-02-01")),
                 value = c(1, 2))
ggplot(df, aes(x = date, y = value)) +
    geom_col() +
    scale_x_date(date_breaks = "1 month", date_labels = "%b")
```

![](https://i.imgur.com/lUHgplF.png)
