### ISSUE TITLE
Reprex with asynchronous functions

### ISSUE THREAD

**Issue by RLesur** [tidyverse/reprex#254]
First of all, thanks for the **reprex** package, I love it!

It seems that making a reprex with asynchronous functions built on top of the [**later**](https://cran.r-project.org/package=later) package is not yet possible. AFAIK, this is not surprising. 
Even if this issue is related to other packages, I fill an issue here to document the consequences on the **reprex** package.

Here are two examples.

#### With the **promises** package
Take this reprex:

``` r
library(promises)
promise_reject("Dummy message")
#> <Promise [rejected: simpleError]>
```

<sup>Created on 2019-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The expected result is:

``` r
library(promises)
promise_reject("Dummy message")
#> <Promise [rejected: simpleError]>
#> Unhandled promise error: Dummy message
```

#### With the later package

``` r
library(later)
later(~ message("Dummy message"), delay = 0)
```

<sup>Created on 2019-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The expected result is:

``` r
library(later)
later(~ message("Dummy message"), delay = 0)
#> Dummy message
```

#### Related issues
- https://github.com/rstudio/rmarkdown/issues/1560 
- https://github.com/rstudio/promises/issues/26

**Comment by jennybc** [comment]
So this sounds like an rmarkdown issue and only affects reprex because reprex uses rmarkdown. I'm glad the implications for reprex are recorded, but it looks like there's no call to action here.
