### ISSUE TITLE
Venue as suffix

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#256]
I find myself doing `reprex(venue = "R")` fairly often, usually for Slack, and I find it aggravating.

Seriously considering having suffix-y forms to specify venue. Something like so:

``` r
reprex_r <- function(...) reprex(..., venue = "R")
reprex_rtf <- function(...) reprex(..., venue = "rtf")
# and so on
```

Would need to think about how this interacts with my keyboard shortcut, but that's more of a personal matter. Shortcut could be rewired to lead to a quick choice of venue, probably console-based.

cc @hadley

**Comment by 11rchitwood** [comment]
I also find myself  `reprex(venue = "R")` often as well. When I [posted on the RStudio Community](https://community.rstudio.com/t/reprex-option-to-change-default-venue/30819/3?u=11rchitwood), someone suggested putting this in my `.Rprofile` as an alternative:

```r
reprex <- purrr::partial(reprex::reprex, venue = "r")
```

I don't like overwriting functions in my `.Rprofile`, but it's a workaround.

Also, I suggested exposing a `default_venue` option for this, but I think separate suffix functions might be a better solution.

**Comment by jennybc** [comment]
> Also, I suggested exposing a default_venue option for this, but I think separate suffix functions might be a better solution.

Yeah, I don't feel like the default would solve it, because I would say my usage is 50/50 `venue = "gh"` and `venue = "r"`. And when I'm making a talk, I also feel friction around `venue = "rtf"`.
