### ISSUE TITLE
Create syntax-highlighted RTF snippets for pasting into, e.g., Keynote

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#26]
I bet `reprex` could package this up nicely ... a gist tweeted by @AmeliaMN on code highlighting for Keynote presentations:

https://gist.github.com/jimbojsb/1630790

I'm going to paste the body here in case the gist goes away. But the comments look pretty useful, e.g. using alternative highlighters like Pygments..
## Step 0:

Get [Homebrew](http://mxcl.github.com/homebrew/) installed on your mac if you don't already have it
## Step 1:

Install highlight. "brew install highlight". (This brings down Lua and Boost as well)
## Step 2:

Highlight your source. "highlight -O rtf myfile.php | pbcopy". This will highlight the source code in RTF format and copy the result of that operation to your Mac's clipboard.
## Step 3:

Paste into your slide in Keynote. Keynote will create a new text box with your highlighted code. You can adjust the width as needed, and adjust the font size with cmd+ and cmd-

**Comment by AmeliaMN** [comment]
+1

**Comment by jennybc** [comment]
@yihui Do you have any thoughts on the basic problem? Which is creating syntax highlighted snippets that are convenient to paste into, say, Keynote. I frequently render to Word, so I can copy and paste with style. And then I still have to fiddle with the text background. It feels ridiculous.

**Comment by yihui** [comment]
I have never used Keynote myself, but I think this is definitely doable (I don't know how to solve the background issue, though; will `highlight -O html` work?). It is possible to write to the clipboard in R (see the "Clipboard" section in `?clipboard`). I don't know if `pygments` is better than `highlight`.

**Comment by romainfrancois** [comment]
Related. https://github.com/romainfrancois/highlight/issues/18
