### ISSUE TITLE
Add tests around encoding

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#262]

**Comment by cderv** [comment]
I have dev reprex installed and some issue still present with encoding on a (French) windows machine. 

The R code to reprex: 
```r
c('≧','⑧','♂')
```

the result of `reprex::reprex()`
``` r
c('?','?','?')
#> [1] "?" "?" "?"
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

The result of `reprex::reprex(input = "test.R")` if I put the code in an R file encoded in utf8
``` r
c('<U+2267>','<U+2467>','<U+2642>')
#> [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

It does not seem right... 

Seems like an edge case, but we had a knitr issue with those character and reprex very difficult to make.

**Comment by jennybc** [comment]
I believe all 3 of these characters are unrepresentable in Latin-1.

And, therefore, I think we're bumping up against the failure modes of various tools in this scenario:

  * `clipr::read_clip()` truly returns the question marks in this case. So that's the input reprex starts with. Below you'll also see an example of where the clipboard output isn't as good as what the `.md` file contains.
  * Input through anything but the clipboard means we get these Unicode escapes.

I *think* reprex is doing as well as it can, i.e. as well as R / knitr / evaluate allows here. I don't think reprex can do any more.

---

I see same result as you for clipboard + `reprex()`.

---

Expression input: `reprex(c('≧','⑧','♂'), advertise = FALSE)`

``` r
c("<U+2267>", "<U+2467>", "<U+2642>")
#> [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

---

UTF-8 encoded input file: `reprex(input = "utf8.R", outfile = NA, advertise = FALSE)`

Contents of the post-`reprex()` clipboard:

``` r
c('<U+2267>','<U+2467>','<U+2642>')
#> [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

Contents of `utf8_reprex.md`:

``` r
c('≧','⑧','♂')
#> [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

---

String input `reprex(input = "c('≧','⑧','♂')\n", advertise = FALSE)`:

``` r
c('<U+2267>','<U+2467>','<U+2642>')
#> [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

---

Even if I use `rmarkdown::render("utf8.R", encoding = "UTF-8")` where `utf8.R` is saved with UTF-8 with these contents:

```
#' ---
#' output: md_document
#' ---


c('≧','⑧','♂')
```

I get this output:

```
 c('≧','⑧','♂')

## [1] "<U+2267>" "<U+2467>" "<U+2642>"
```

**Comment by jennybc** [comment]
@cderv Can you find any evidence that reprex is making things worse? I think reprex has hit the fundamental limits of the tools I'm working with and harsh realities about Windows.

**Comment by jennybc** [comment]
Also, I've pushed even more changes, so you should update again. But I ran all of the above with the latest version.

**Comment by jennybc** [comment]
A test has been added in 60e03dfac412dbfcce83b16f29d816d07a2cfe8e and extended in 68c8622b747ef380698ad382e4dd3b18d6fece9a. I have confirmed failure of these expectations with dev reprex prior to (e10e55389f15421e5956151d3f7854703a0ea622 + 9af34044f8970959e02907d80a76be592c990ff9), i.e. it's a meaningful test.

**Comment by cderv** [comment]
You're right. I think it is a really an edge case. I having issue with knitr and rmarkdown with those string. 

FWIW, I got the exact same results as you with last dev version of reprex. I am glad you found some tests for encoding ! 👍
