### ISSUE TITLE
Error when _R_CHECK_LENGTH_1_LOGIC2_=true

### ISSUE THREAD

**Issue by jayhesselberth** [tidyverse/reprex#267]
This generates an error, looks like the same bug as https://github.com/r-lib/pkgdown/issues/1064

``` r
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "true")

reprex::reprex()
```

I think you'll have to collapse the template before calling `whisker.render` in `apply_template()`.

**Comment by jennybc** [comment]
This has now been fixed upstream in whisker:

https://github.com/edwindj/whisker/commit/9144a35466ef3716437e050356d90cb0108d07da

and that change is on CRAN as of whisker v0.4.
