### ISSUE TITLE
After running `reprex()` the value `ok = TRUE` appears in the global environment

### ISSUE THREAD

**Issue by andresrcs** [tidyverse/reprex#269]
Every time I use `reprex()` a value is left behind in my global environment `ok = TRUE`, I'm assuming this is not by design or is it?

![image](https://user-images.githubusercontent.com/14981085/60758689-d31e1c00-9fdf-11e9-9cd3-da8908fc21c7.png)

`reprex` version = 0.3.0

**Comment by jennybc** [comment]
No, not intended. It's not immediately clear to me where it's coming from or who's doing it. A quick search of the reprex source doesn't reveal any obvious candidates, i.e. I can't find any statements involving `ok <-` or similar 🤔

Debugging, I can determine that it happens during the call to `reprex_render()`, which is a thin wrapper around  `callr::r_safe()`. @gaborcsardi: can you think of any reason why someone is writing `ok` into global env?

**Comment by gaborcsardi** [comment]
Fixed already in dev processx. Will submit a new version tomorrow.

**Comment by jennybc** [comment]
OK thanks all!
