### ISSUE TITLE
Switch to shiny based alert for error

### ISSUE THREAD

**Issue by ColinFay** [tidyverse/reprex#273]
My console is on the top right side of my RStudio. 

When I launch the reprex addin and have a `{yesno}` question, I always miss the question, as the addin hides the console:

![Screenshot 2019-07-16 at 11 09 46](https://user-images.githubusercontent.com/17936236/61281632-3ff09d80-a7ba-11e9-9151-5814a53531e4.png)

So in this case I always stare at my screen for a couple of seconds before realising that something has happened in my console, and I have to move around my addin to see: 

![Screenshot 2019-07-16 at 11 10 36](https://user-images.githubusercontent.com/17936236/61281690-5d256c00-a7ba-11e9-83b3-0f3263672a89.png)

And once I've done that, the console waits for me to enter something, but I can't as the addin is blocking me from accessing the console. 

If I click on "Cancel", nothing happens. If I click on "Render", nothing happens. Both these buttons are designed to execute R code, but the console is waiting for an input.  I have to click on the cross to close the addin and enter things in the console. 

I feel switching to a shiny-based alert system (which would be quite straightforward to implement in JS) would be a better user-experience for these kinds of cases.

**Comment by jennybc** [comment]
I think I have designed this particular problem away by never posing this sort of yes / no question anymore 😁
