### ISSUE TITLE
Change the default for `std_out_err` to allow seeing the stderr

### ISSUE THREAD

**Issue by mattfidler** [tidyverse/reprex#279]
Feel free to open a new issue about whether to change the default for `std_out_err` and/or to put it under the control of an option. I'm hesitant to turn it on by default, because now we're vulnerable to any glitches in how that works in callr. So I lean towards: keep the default as `FALSE` but make it possible for people who frequently reprex with packages where they need `std_out_err` to set a personal default of `TRUE`.

_Originally posted by @jennybc in https://github.com/tidyverse/reprex/issues/278#issuecomment-517815558_

**Comment by mattfidler** [comment]
My personal opinion is to turn it on since users may not know about if they need to turn on/off `std_out_err`.  However the issues in `callr` may not be trivial.

**Comment by jennybc** [comment]
I took a look at this and realized this already **is** under the control of an option!

So including code like this in one's `.Rprofile`:

```
options(
  reprex.std_out_err = TRUE
)
```

would change your personal default to `std_out_err = TRUE)`. Having played with that a bit, I stand by my position that a default of `FALSE` is best for most people. In addition to the concerns raised above, most reprexes won't have any content there and it just creates clutter. Here's the result of `reprex(1)` with `options(reprex.std_out_err = TRUE)` in my `.Rprofile`: 

``` r
1
#> [1] 1
```

standard output and standard error
``` sh
-- nothing to show --
```
<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
