### ISSUE TITLE
accommodate renv projects with reprex?

### ISSUE THREAD

**Issue by kevinushey** [tidyverse/reprex#284]
From https://github.com/rstudio/renv/issues/208.

Projects using `renv` typically require some extra gymnastics, which are performed (normally) through the use of a project `.Rprofile`. However, `reprex()` does not read that `.Rprofile` by default, leading to some subtle differences in how `reprex()` runs code versus how `renv` might run that same code.

It could be worth considering whether `reprex()` could support this by default; e.g. by allowing the project `.Rprofile` to be loaded -- either by default, or when it detects or knows `renv` is active.

**Comment by jennybc** [comment]
Jotting down ideas for what `reprex_renv()` could do:

  * Always set `outfile = NA` or take some other measure so that working directory is inherited, not set to session temp dir.
  * Prepend the user's code with an `include = FALSE` chunk that sources project `.Rprofile`.

**Comment by jennybc** [comment]
I'm going to look at this soon @kevinushey. Will you read it over again and update if renv or your thinking has evolved?

**Comment by kevinushey** [comment]
Thanks! I think there are two possible approaches here:

1. Ensure the new R session is launched in the project root directory, so that the project `.Rprofile` is sourced and used. (For `renv` projects, if that file exists, it will automatically load that project, set up library paths, and so on.)

2. Rather than changing the working directory for the process, just explicitly call `renv::load("/path/to/project")` before running the reprex code. This would ensure that `renv` reprex's work even if the user has disabled the `renv` auto-loader in the project `.Rprofile`.

**Comment by jennybc** [comment]
I didn't end up doing anything specific to renv here. I just rationalized reprex's behaviour in light of `callr::r()`'s default behaviour re: executing `.Rprofile` in working directory.
