### ISSUE TITLE
Poor handling of cli symbols

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/reprex#285]
cc @lionel- as you might have thoughts too

vctrs (and really rlang under the hood) has begun incorporating cli symbols into error messages to make them more informative. For whatever reason, these bork reprex.

Run `reprex::reprex(venue = "r")` on this code chunk with the current development version of vctrs (the `gh` venue fails too).

```r
library(vctrs)

vec_as_index(1:2, 1L)
```

The output should look like this:

![Screen Shot 2019-10-20 at 11 25 58 AM](https://user-images.githubusercontent.com/19150088/67161847-6891b180-f32c-11e9-95de-38319b3d6005.png)

But reprex get's confused and gives me this back:

```
#' \`\`\`r
#' library(vctrs)

#' vec\_as\_index(1:2, 1L)
#' \#\> \`\`\`
```

With this in my viewer:

![Screen Shot 2019-10-20 at 11 28 02 AM](https://user-images.githubusercontent.com/19150088/67161875-b5758800-f32c-11e9-8f6d-953580bdc9e7.png)

I'm on the development version of reprex.

**Comment by lionel-** [comment]
Does setting `options(cli.unicode = FALSE)` solve it?

**Comment by DavisVaughan** [comment]
Actually no

```r
library(vctrs)
options(cli.unicode = FALSE)
vec_as_index(1:2, 1L)
```

gives me the following with `reprex::reprex(venue = "r")`

```
#' `r library(vctrs) options(cli.unicode = FALSE) vec_as_index(1:2, 1L) #>`
```

**Comment by jennybc** [comment]
🤨

**Comment by jennybc** [comment]
I just tried what you said @DavisVaughan and I get the correct outcome:

``` r
library(vctrs)

vec_as_index(1:2, 1L)
#> Error: Must index existing elements.
#> ✖ Can't subset position 2.
#> ℹ There are only 1 elements.
```

<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

Maybe this got fixed?

**Comment by DavisVaughan** [comment]
Works for me now with dev vctrs and reprex 🤷‍♂ 

``` r
library(vctrs)

vec_as_index(1:2, 1L)
#> Error: Must index existing elements.
#> ✖ Can't subset position 2.
#> ℹ There are only 1 elements.
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
