### ISSUE TITLE
Workflow based on .Rmd, as opposed to .R

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#287]
Various reasons it might be interesting to offer a workflow that is `.Rmd`-based:

  * User is more comfortable in `.Rmd`. @Hadley had some thoughts about this, based on talking to @mine-cetinkaya-rundel.
  * Chunks could take advantage of knitr/rmarkdown's support for languages other than R.

**Comment by mine-cetinkaya-rundel** [comment]
Here is where I've gathered my thoughts about this: https://github.com/mine-cetinkaya-rundel/rmd-reprex. I'd be happy to move the info from there to this issue and keep the conversation here if helpful.

**Comment by jennybc** [comment]
Hmm, that is considerably more involved than what I had in mind @mine-cetinkaya-rundel. I suppose that what I'm thinking of is the lower-level functionality that would be necessary for you to create the addin you describe there. As it stands, reprex knows nothing about Rmd.

**Comment by MikeKSmith** [comment]
As a workaround for examples that are simple enough: 
knitr::purl("reprex.Rmd", documentation=2) %>% reprex::reprex(input = .)

**Comment by jennybc** [comment]
Now that `reprex_document()` and `reprex_render()` exist, we have a basic `.Rmd` workflow. So the purling example would not be necessary.

I'm pretty sure I should have closed this when I merged #291, but perhaps I've left it open because I want to add more docs.

**Comment by jennybc** [comment]
I still can't tell why I left this open, so I'll close it.
