### ISSUE TITLE
Tidyr pivot_longer and pivot_longer_spec feature request

### ISSUE THREAD

**Issue by chester-gan** [tidyverse/reprex#296]
Specific feature request: please enable pivot_longer's values_ptypes argument to handle exceptional cases whereby the input columns used to generate the variables generated from values_to are not of the same type.

```r
dataframe %>% 
      # drop nonsensical columns that are completely empty
      select(
        -matches("x\\d+|v\\d+")
      ) %>% 
      # If a variable's measurement number is not given (i.e. variable name 
      # does not have pattern "_\\d+$"), then assume that, for that variable,
      # one and only one measurement is taken, and it is the first.
      rename_at(
        vars(matches("_C\\d+$")),
        ~paste0(., "_1")
      ) %>% 
      pivot_longer(
        cols = matches("_\\d+$"),
        names_to = c(".value", "event_name_multiple_events", "CRF version", "reading"),
        names_pattern = "(.*)_(E\\d_\\d)_(C\\d+)_(\\d+$)",
        values_ptypes = list(ics_laba = character()),
        values_drop_na = TRUE
      )
# Code breaks at pivot_longer because some input columns of the dataframe that are used to #generate one of the values_to variables are not of the same type. Should include a scalable #exception handler in this case.
```

**Comment by jennybc** [comment]
This seems like an issue that belongs in tidyr. The reprex package makes no judgments and has no control over how any specific package or function throws its errors.

<https://github.com/tidyverse/tidyr/issues>

**Comment by chester-gan** [comment]
> This seems like an issue that belongs in tidyr. The reprex package makes no judgments and has no control over how any specific package or function throws its errors.
> 
> https://github.com/tidyverse/tidyr/issues

@jennybc Hadley told me to file an issue with reprex (see https://github.com/tidyverse/tidyr/issues/800)

**Comment by jennybc** [comment]
Sorry I think we are having semantic miscommunications 😖

I think this is the message: if you have an issue, open a new issue in **tidyr**, backed by a relevant reproducible example, preferably using the reprex package (because it has nice ergonomics for us).

**Comment by chester-gan** [comment]
> Sorry I think we are having semantic miscommunications 😖
> 
> I think this is the message: if you have an issue, open a new issue in **tidyr**, backed by a relevant reproducible example, preferably using the reprex package (because it has nice ergonomics for us).

Noted.
