### ISSUE TITLE
reprex fails if a comment starts with `-` and contains a single or double quote

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/reprex#308]
I couldn't find if comments starting with `-` are special but this crashes without helpful error : 

minimal example :

    #-' 

In Rstudio this error will pop up

> R Code execution error 

then in the console : 

> Rendering reprex...
> 
>Error: <callr_status_error: callr subprocess failed: <text>:1:8: unexpected INCOMPLETE_STRING
>1: alist( ' )
>           ^>
>-->
><callr_remote_error in parse(text = code, keep.source = FALSE):
> <text>:1:8: unexpected INCOMPLETE_STRING
>1: alist( ' )
>           ^>
> in process 27376 
>
> See `.Last.error.trace` for a stack trace.

The realistic case will be in the form of 

    #---- This shouldn't fail

Strangely pairing the simple quote will work if we have a single `-`

```
#-'this will work'
#--'this will fail'
#-x'this will fail'
```

The case of double quotes behaves a bit differently

```
#-"this will fail
#- "this will fail
#-"this will work"
#--"this will work
#-x"this will work
```

**Comment by jennybc** [comment]
This is really a knitr phenomenon and has nothing to do with reprex.

``` r
> knitr::spin(text = c("#-'", "1:3"))
(*) NOTE: I saw chunk options "'"
 please go to https://yihui.name/knitr/options
 (it is likely that you forgot to quote "character" options)
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:8: unexpected INCOMPLETE_STRING
1: alist( ' )
           ^
```

Knitr uses special comment syntax to allow for chunk options to be specified in `.R` files. So I think you need to avoid syntax that knitr dislikes inside code that will eventually be processed with knitr.
