### ISSUE TITLE
error when rendering ggplotly

### ISSUE THREAD

**Issue by david-romano** [tidyverse/reprex#317]
When I try to apply `reprex()` to this code
```
library(tidyverse)
library(gapminder)
library(plotly)
p <- gapminder %>% 
  ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point(aes(color = country), show.legend = FALSE)
ggplotly(p)
```
I get the following error:
```
Rendering reprex...
 
Error: callr subprocess failed: Functions that produce HTML output found in document targeting markdown_strict output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: true

Note however that the HTML output will not be visible in non-HTML formats.
```
Since it's `reprex()` that's creating the rmarkdown file internally, how would one modify this option?

**Comment by jennybc** [comment]
Does your code work in a regular `.Rmd` document where the output format is markdown? Because that is a prerequisite for reprex happiness, which is fundamentally targeting markdown output.

**Comment by david-romano** [comment]
It does, although in the case of several of my students who use Windows, the `ggplotly()` output doesn't even render in RStudio's 'Viewer' pane.  The reprex issue, however, is shared by everyone in the class, independent of OS.

**Comment by jennybc** [comment]
Can you post an entire `.Rmd` then for me, completely with yaml?

**Comment by david-romano** [comment]
This works to post on SO, so I hope it does here, too:
````
---
title: "ggplotly example"
author: "Me"
date: "February 28, 2020"
output: html_document
---

```{r  include=FALSE}
library(tidyverse)
library(gapminder)
library(plotly)
p <- gapminder %>% 
  ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point(aes(color = country), show.legend = FALSE)
```
```{r}
ggplotly(p)
```
````

**Comment by jennybc** [comment]
So, I'm going to go back to this question.

> Does your code work in a regular .Rmd document where the output format is markdown?

In the above, the output format is _not_ markdown. It's `html_document`.

**Comment by david-romano** [comment]
Sorry: Since I've only created .Rmd files through the RStudio GUI, the only choices available have been html, pdf, and Word, so I misunderstood your original question -- what value should I use to specify markdown as output format?

**Comment by jennybc** [comment]
You could do `output: md_document` instead of `output: html_document`.

(These are all the different built-in output formats: <https://rmarkdown.rstudio.com/docs/reference/index.html#section-output-formats>)

**Comment by david-romano** [comment]
That gives the same error -- does this mean that `ggplotly()` must simply be incompatible with `reprex()`?

**Comment by jennybc** [comment]
It means that the type of object you're making requires a full html environment (so rendering to an html document type). I assume it's making some sort of html widget?

If so, yes, it's never going to work when rendering to a markdown format, which is what reprex does. reprex just exposes a specific subset of rmarkdown and takes care of lots of points of friction. But if you can't get a piece of code to render to markdown with `rmarkdown::render()`, it won't work within reprex either.

It sounds like you truly need html.

**Comment by david-romano** [comment]
Thanks, I appreciate the time you took to walk through this with me -- it hadn't occurred to me that there might be contexts that are out of reach of reprex!

**Comment by Bisaloo** [comment]
I encountered the same issue while testing the new [flow package](https://github.com/moodymudskipper/flow). 

After reading this thread, it makes total sense why this doesn't work but I think a less cryptic error message would be really helpful (if possible)!
