### ISSUE TITLE
Feature Request - Redaction of Personal Information

### ISSUE THREAD

**Issue by j450h1** [tidyverse/reprex#318]
I'm often sharing reprexes for client work and, after creating a reprex,need to manually redact things such as the client's name, Google Cloud project name, bucket addresses, email addresses, local file paths, etc. Would be great if there was a way to specify what you want redacted automatically (or somewhat automatically..). or keep track of a list of words/patterns you want redacted somewhere.

**Comment by jennybc** [comment]
You can use the usual techniques for setting chunk options in `.R` files, which is to preface them with `#+`.

This is demonstrated in the [examples for reprex](https://reprex.tidyverse.org/reference/reprex.html) (although for a different purpose) and in the [reprex guide for googlesheets4](https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html#use-a-private-sheet) (for exactly your purpose).

Example:

This `reprex()` call:

``` r
reprex({
  #+ secret, include = FALSE
  this <- "a super duper secret thing"
  
  #+ actual-reprex-code
  exists(this)
  nchar(this)
})
```

yields this output (super secret stuff happens but is hidden)

``` r
exists(this)
#> [1] FALSE
nchar(this)
#> [1] 26
```

<sup>Created on 2020-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
