### ISSUE TITLE
Can javascript be used in a reprex (with venue = 'html')?

### ISSUE THREAD

**Issue by rpruim** [tidyverse/reprex#321]
I get an error from `callr` when I try to make a reprex from this

```r
data.frame(
  category = LETTERS[1:4],
  count = 1:4) %>%
  reactable::reactable()      # works without the reactable() but not with it
```

```r
reprex::reprex(venue='html')
```

```
Rendering reprex...
Error: callr subprocess failed: Functions that produce HTML output found in document targeting commonmark output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: true

Note however that the HTML output will not be visible in non-HTML formats.
```

If I omit the call to `reactable::reactable()` then it works.

I've tried both version 3.2.0 and 3.4.3 of `callr`.

**Comment by jennybc** [comment]
No, reprex is very markdown-focused. The html venue is more like one last little bonus conversion step we can take for you, but it really needs to be low-tech html fragment.

**Comment by rpruim** [comment]
Thanks.  That's what I was guessing, but I wanted to make sure it wasn't a bug or something I was overlooking.
