### ISSUE TITLE
<style> block from gt is not hidden in GitHub

### ISSUE THREAD

**Issue by jayhesselberth** [tidyverse/reprex#324]
The `<style>` block is hidden in RStudio viewer, but not when pasted into GitHub.

Is this fixable?

``` r
library(gt)
library(tidyverse)

# Define the start and end dates for the data range
start_date <- "2010-06-07"
end_date <- "2010-06-14"

sp500 %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  gt()
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#zlpqrktqzw .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zlpqrktqzw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zlpqrktqzw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zlpqrktqzw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zlpqrktqzw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zlpqrktqzw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zlpqrktqzw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zlpqrktqzw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zlpqrktqzw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zlpqrktqzw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zlpqrktqzw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zlpqrktqzw .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#zlpqrktqzw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zlpqrktqzw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zlpqrktqzw .gt_from_md > :first-child {
  margin-top: 0;
}

#zlpqrktqzw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zlpqrktqzw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zlpqrktqzw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#zlpqrktqzw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zlpqrktqzw .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#zlpqrktqzw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zlpqrktqzw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zlpqrktqzw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zlpqrktqzw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zlpqrktqzw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#zlpqrktqzw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zlpqrktqzw .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#zlpqrktqzw .gt_left {
  text-align: left;
}

#zlpqrktqzw .gt_center {
  text-align: center;
}

#zlpqrktqzw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zlpqrktqzw .gt_font_normal {
  font-weight: normal;
}

#zlpqrktqzw .gt_font_bold {
  font-weight: bold;
}

#zlpqrktqzw .gt_font_italic {
  font-style: italic;
}

#zlpqrktqzw .gt_super {
  font-size: 65%;
}

#zlpqrktqzw .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="zlpqrktqzw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

date

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

open

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

high

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

low

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

close

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

volume

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

adj\_close

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

2010-06-14

</td>

<td class="gt_row gt_right">

1095.00

</td>

<td class="gt_row gt_right">

1105.91

</td>

<td class="gt_row gt_right">

1089.03

</td>

<td class="gt_row gt_right">

1089.63

</td>

<td class="gt_row gt_right">

4425830000

</td>

<td class="gt_row gt_right">

1089.63

</td>

</tr>

<tr>

<td class="gt_row gt_left">

2010-06-11

</td>

<td class="gt_row gt_right">

1082.65

</td>

<td class="gt_row gt_right">

1092.25

</td>

<td class="gt_row gt_right">

1077.12

</td>

<td class="gt_row gt_right">

1091.60

</td>

<td class="gt_row gt_right">

4059280000

</td>

<td class="gt_row gt_right">

1091.60

</td>

</tr>

<tr>

<td class="gt_row gt_left">

2010-06-10

</td>

<td class="gt_row gt_right">

1058.77

</td>

<td class="gt_row gt_right">

1087.85

</td>

<td class="gt_row gt_right">

1058.77

</td>

<td class="gt_row gt_right">

1086.84

</td>

<td class="gt_row gt_right">

5144780000

</td>

<td class="gt_row gt_right">

1086.84

</td>

</tr>

<tr>

<td class="gt_row gt_left">

2010-06-09

</td>

<td class="gt_row gt_right">

1062.75

</td>

<td class="gt_row gt_right">

1077.74

</td>

<td class="gt_row gt_right">

1052.25

</td>

<td class="gt_row gt_right">

1055.69

</td>

<td class="gt_row gt_right">

5983200000

</td>

<td class="gt_row gt_right">

1055.69

</td>

</tr>

<tr>

<td class="gt_row gt_left">

2010-06-08

</td>

<td class="gt_row gt_right">

1050.81

</td>

<td class="gt_row gt_right">

1063.15

</td>

<td class="gt_row gt_right">

1042.17

</td>

<td class="gt_row gt_right">

1062.00

</td>

<td class="gt_row gt_right">

6192750000

</td>

<td class="gt_row gt_right">

1062.00

</td>

</tr>

<tr>

<td class="gt_row gt_left">

2010-06-07

</td>

<td class="gt_row gt_right">

1065.84

</td>

<td class="gt_row gt_right">

1071.36

</td>

<td class="gt_row gt_right">

1049.86

</td>

<td class="gt_row gt_right">

1050.47

</td>

<td class="gt_row gt_right">

5467560000

</td>

<td class="gt_row gt_right">

1050.47

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
This appears to be a "feature" of gt and/or rmarkdown and/or knitr. Not reprex. The same thing happens if you put that code into an `.Rmd` and specify any of the markdown formats (e.g. `output: md_document`). I think the decision to not include the `<style>` block when rendering to a format that doesn't support it needs to be made upstream.
