### ISSUE TITLE
Make `tidyverse_quiet` also quiet tidymodels startup messages?

### ISSUE THREAD

**Issue by juliasilge** [tidyverse/reprex#326]
What would you think about the `tidyverse_quiet` option also setting `tidymodels.quiet`? I don't know that having a separate option makes a lot of sense, but folks who don't want their reprexes to be filled with tidyverse startup message probably don't want them to have tidymodels start up messages either. 

Our current startup message looks something like this:

``` r
library(tidymodels)
#> ── Attaching packages ─────────────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.0          ✓ recipes   0.1.13    
#> ✓ dials     0.0.8          ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.3     
#> ✓ ggplot2   3.3.2          ✓ tidyr     1.1.0     
#> ✓ infer     0.5.3          ✓ tune      0.1.1.9000
#> ✓ modeldata 0.0.2          ✓ workflows 0.1.2     
#> ✓ parsnip   0.1.2.9000     ✓ yardstick 0.0.7     
#> ✓ purrr     0.3.4
#> ── Conflicts ────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
```

<sup>Created on 2020-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jennybc** [comment]
Hmm. It's hard to decide if it should get its own option. In terms of meaning what you say and saying what you mean, it seems like it should. But I also agree it seems like the user's wishes for the two would typically be the same. Maybe bring this up in slack and/or poll our team?

**Comment by juliasilge** [comment]
We chatted and the plan is to extend the `tidyverse_quiet` option of reprex to also control the tidymodels option `tidymodels.quiet`. I'll submit a PR soon.
