### ISSUE TITLE
Indentation vs. backticks?

### ISSUE THREAD

**Issue by pat-s** [tidyverse/reprex#330]
Hi,

recently when calling `reprex(venue = "gh")` I get an indented output for every reprex (i.e. with four whitespaces) instead of the three backticks for code encapsulation.
This results in in no code highlighting when pasting into GitHub and also a wrong indentation.

I am on the latest GitHub ref and wondering what might be wrong in my local settings since nobody else reported this so far.
Could it be that the latest RStudio dailies have an effect on this? (I do not want to go back to the current stable atm just to test this).

Below is an example. If I add ```r to this block for code highlighting, the following code lines are getting accidentally indented. (You can view the raw code by trying to edit this comment)

    library(mapview)
    #> GDAL version >= 3.1.0 | setting mapviewOptions(fgb = TRUE)
    library(tidyverse)
    library(sf)
    #> Linking to GEOS 3.8.1, GDAL 3.1.2, PROJ 7.1.0

    franconia %>%
      group_by(district) %>%
      summarize() %>%
      mutate(area = st_area(.) / 1e6) %>%
      mapview(zcol = "area")
    #> `summarise()` ungrouping output (override with `.groups` argument)
    #> Error in Ops.units(lim, prop * d * c(-1, 1)): both operands of the expression should be "units" objects

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by cderv** [comment]
You're not the only one. I also observed this and not in the preview IDE. I was just looking at it yesterday to try finding what has changed.

**Comment by jennybc** [comment]
@Hadley has seen it too, I think.

But I have not.
So I don't think it's reprex that's changed. I think it's something else?

**Comment by cderv** [comment]
oh ok. I'll look into this. I could be pandoc related.

**Comment by cderv** [comment]
Yes this comes from newer version of pandoc than 2.7.3. I use 2.10.1 as default, and if I switched back to 2.7.3 it works as expected. 
I tested with CRAN reprex, and it uses `commonmark` output format. Reader and Writer for commonmark have some changes in last pandoc (with a new `commonmark_x` format available.

I'll look into dev version to see what is happening.

**Comment by cderv** [comment]
It could be a pandoc issue as the output is now different 

```` r
infile <- tempfile(fileext = ".md")
outfile <- tempfile(fileext = ".md")
xfun::write_utf8(c(
  "```r", 
  "fun <- function(x) mean(x)",
  "```"
), infile)

rmarkdown::find_pandoc(version = "2.10.1")
#> $version
#> [1] '2.10.1'
#> 
#> $dir
#> [1] "C:/Users/chris/scoop/shims"
rmarkdown::pandoc_convert(infile, to = "commonmark", output = outfile)
xfun::file_string(outfile)
#>     fun <- function(x) mean(x)

rmarkdown::find_pandoc(version = "2.7.3")
#> $version
#> [1] '2.7.3'
#> 
#> $dir
#> [1] "C:/Program Files/RStudio/bin/pandoc"
rmarkdown::pandoc_convert(infile, to = "commonmark", output = outfile)
xfun::file_string(outfile)
#> ``` r
#> fun <- function(x) mean(x)
#> ```

unlink(c(infile, outfile))
````

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In [pandoc-announce](https://groups.google.com/g/pandoc-announce/c/aDKyXI3QFTg), it was explicit that there could be some issues. 

> We no longer depend on cmark-gfm (which wraps a C library)
for commonmark and gfm parsing and rendering. For parsing
commonmark and gfm, we now use commonmark-hs, my pure
Haskell commonmarking parsing library, which supports many
of the pandoc extensions. For rendering, we rely on the
markdown writer, which when supplied with appropriate
extensions and options generates correct commonmark. **If you
notice anything amiss in commonmark or gfm translations,
please report them as there may be some rough edges in this
transition.** The upside, however, is that we now support
many more extensions for commonmark and gfm.

@pat-s are you also using pandoc 2.10.1 by any chance ?

**Comment by cderv** [comment]
And I think this was an issue in last pandoc and this will be fixed in the next pandoc version 
https://github.com/jgm/pandoc/commit/2077739a35fd51ca6f482ce8a108d10799f5b274

**Comment by jennybc** [comment]
Thanks @cderv for getting to the bottom of it.

So I think this is a closed issue as far as reprex is concerned. The advice is not use the semi-borked version of Pandoc, that lost the ability to write fenced code blocks.

**Comment by pat-s** [comment]
> @pat-s are you also using pandoc 2.10.1 by any chance ?

Good guess with `pandoc`.
Yes, it is the current version on macOS, hence I guess many more people are facing the issue currently.

Good to know the fix is already implemented and thank for digging in!

**Comment by cderv** [comment]
I can't try for sure the fix but as `fenced_code_attributes` was missing and has been added now, I guess it will work again. 
Also, the commit message relates directly to the issue here.

However, there could be some adjustment because I am unclear if `commonmark` or the new `commonmark_x` should be use in reprex with newer pandoc. Anyway, RStudio ships with 2.7.3 but rmarkdown use the highest available version. I am not sure there is way to tell reprex to use a specific pandoc yet - `find_pandoc` won't work because `render` is done in another R session with `callr`. You could set the value `Sys.getenv("RSTUDIO_PANDOC")` to be first in the PATH when you render a reprex. That should work. 
``` r
withr::with_path(Sys.getenv("RSTUDIO_PANDOC"), rmarkdown::find_pandoc())
#> $version
#> [1] '2.7.3'
#> 
#> $dir
#> [1] "C:/Program Files/RStudio/bin/pandoc"
```

<sup>Created on 2020-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Anyway, I will check al this as soon as the next pandoc version is released.
