### ISSUE TITLE
Can't install reprex from GitHub

### ISSUE THREAD

**Issue by carlmorgenstern** [tidyverse/reprex#334]
---

Can't install reprex from GitHub after generating and installing GITHUB_PAT

> devtools::install_github("tidyverse/reprex")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'reprex' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 51/60
  Rate limit reset at: 2020-10-03 17:29:36 UTC

-----

**Comment by jennybc** [comment]
I would interpret this to mean that your GitHub PAT is invalid.
