### ISSUE TITLE
Feature request: venue = "piazza"

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/reprex#335]
I'd love to have more students using reprex when asking questions on Piazza, and I think there may be two challenges with it that the reprex package could potentially address. The biggest challenge, of course, is making a reprex, but that's on me to teach. Note that I'm primarily focusing on intro students who are learning R via R Markdown documents.

Currently, `venue = "gh"` works on Piazza out of the box, and it's what I use when I respond to student questions. However, I think the following could help student adoption:

1. Offer `venue = "piazza"`, even if it's just an alias to `venue = "gh"`: There are two reasons for this: (1) it might help buy-in and (2) it might help reduce confusion in a course where we're using GitHub as well but not for the purpose of general Q&A and there are already too many tool names to keep track of that it would be nice to not have to say "to post on Piazza use the GitHub venue for your reprex".

2. `venue = "gh"` works but `venue = "piazza"` could be formatted to be more aligned with R Markdown and more robust to student error:

Suppose I have the following code that I want to reprex:

```r
x <- 2
x * 2
plot(cars)
```

If I run this through `venue = "gh"` I get the following

```
    x <- 2
    x * 2
    #> [1] 4
    plot(cars)

![](https://i.imgur.com/BKttr08.png)

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

which works both on GitHub and on Piazza. However, it requires that (1) there is a line break between this and any potential text above it (2) that students understand that indented text will be formatted as code. I'm finding both of these challenging with my students. A slightly modified output that would also work on Piazza is as follows (but imagine there isn't a space between the first and the second ` in):

```
` ``
x <- 2
x * 2
#> [1] 4
plot(cars)
` ``
![](https://i.imgur.com/J99dF3Z.png)

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

Having explicit fences makes it robust to (1) above (code formatting works with and without a space between text and code) and, I think, also addresses (2) where students learn in Rmd documents that "code goes in chunks".

I'm wondering if supporting this sounds reasonable for reprex, and if so, if you'd prefer a PR.

**Comment by jennybc** [comment]
The first thing that I notice is that I suspect part of the friction you are attributing to the need for a piazza venue comes from something entirely different, namely that there's a basically broken Pandoc version floating around and I suspect that you have it:

https://github.com/tidyverse/reprex/issues/330

I'll come back in a bit to say more ...

**Comment by jennybc** [comment]
I'm back. I think your point 2. is really a Pandoc version problem, which hopefully you can check and confirm.

As for point 1, I'm reluctant to add a venue that is just an alias for `"gh"`, which is the default. I probably wouldn't introduce a `"so"` venue today, since it is now the same as `"gh"` (that was not originally the case). And indeed, if reprex started today, the default venue would probably be something "commonmark". It seems like your students can remain fairly unaware of the venue concept, i.e. they can just use `reprex()`. Does that sound right?

**Comment by mine-cetinkaya-rundel** [comment]
Re (2) - I think that's true. I have pandoc `2.10.1` locally, RStudio Cloud is using `2.7.3` (same versions mentioned in the issue you linked to).

Of course, this has now reminded me that reprex is additionally more difficult on Cloud. I'll close this issue for now but if you have any advice on using reprex on Cloud (other than reading from a file or providing code directly as expression), I'd love to hear it.
