### ISSUE TITLE
Make color available -- particularly for use with waldo::compare()

### ISSUE THREAD

**Issue by brshallo** [tidyverse/reprex#339]
I would like the output when using `waldo::compare()` within a reprex to show color.

Current `waldo` output when rendered with `reprex`:
``` r
waldo::compare(c("a", "b", "c"), c("a", "B", "c"))
#> `old`: "a" "b" "c"
#> `new`: "a" "B" "c"
```

Preferred reprex output:

![image](https://github.com/r-lib/waldo/raw/master/man/figures/README/unnamed-chunk-4.svg)
*(from `waldo`s README where it seems it was generated using `asciicast`: [link](https://github.com/r-lib/waldo/blob/master/README.Rmd))*

## Context + previous tweet

I've previously tweeted asking about this feature in regards to `diffobj`, see @brodieG response and example with `diffobj`: https://twitter.com/JennyBryan/status/1259122012506603521 

@jennybc response on that thread: 
>it looks like diffobj's niftiness comes very much from html and css and reprex is "just" convenience wrapper for producing md, at its very heart so I suspect if you need actual html features, you might as well make an Rmd yourself... 
>...it would require analysis both of "does it work?" and whether there's a compelling reason to use reprex in this way... reprex already has support for an `html` venue, but the reason & support is fairly superficial

I opened this issue wondering if the feature request may be more justifiable in the context of recent development on `waldo`.

**Comment by jennybc** [comment]
What reprex venue do you have in mind? As in, literally, the value of the `venue` argument of `reprex::reprex()`.

**Comment by jennybc** [comment]
I don't think this is in scope for reprex. That could conceivably change, as the surrounding world changes, e.g. as [downlit](https://downlit.r-lib.org) matures. But right now there's no reasonable path for reprex to provide this. The main venue remains markdown, which doesn't support color. So this would only work for HTML and RTF and the necessary tooling just isn't in place today.
