### ISSUE TITLE
BBCode support

### ISSUE THREAD

**Issue by mcanouil** [tidyverse/reprex#350]
Hi,

I am using the reprex package frequently (thanks for this wonderful package) and mostly in a forum using BBCode.
I forked and added support to BBCode, but it's more of a hack than anything else (see `pp_md_to_bb()` function).

I wonder if there is a better way to support BBCode in reprex.
If not, I'll be happy to make a PR with the following chunks of codes (which only translate images and code blocks to BBCode).

* In `R/reprex_render.R` 
    ``` r
    pp_md_to_bb <- function(input) {
      bbout_file <- bb_file(input)
      output_lines <- read_lines(md_file(input))
      output_lines[grep("^``` r$", output_lines)] <- "[code=php]" # php is to add syntax coloration in legacy BBCode forum, before they added R
      output_lines[grep("^```$", output_lines)] <- "[/code]"
      output_lines <- gsub("^!\\[\\]\\((.+)\\)$", "[img]\\1[/img]", output_lines)
      write_lines(output_lines, bbout_file)
      bbout_file
    }
    ```
    With the following in `reprex_render_impl()`
    ``` r
      if (venue == "bb") {
        reprex_file <- pp_md_to_bb(input)
      }
    ```

* In `R/venues.R`
    ``` r
    #' @export
    #' @rdname reprex_venue
    reprex_bb <- function(...) reprex(..., venue = "bb")
    ```

* In `R/utils-io.R`
    ``` r
    bb_file <- function(path) {
      path_mutate(path, suffix = "reprex", ext = "txt")
    }
    ```

Best regards,
Mickaël

**Comment by jennybc** [comment]
I'm not sure yet if I'm willing to support a BBCode `venue`. It seems a bit niche, but it also looks like a very modest amount of code gets the job done (thanks for showing that). So I'll let this age. The only `venue` I'm going to add for v1.0.0 (coming very soon) is Slack (#272). I also think Jira would probably be a higher priority (#265, #288).

*Maybe you want to express your proposal as a PR? That makes it even more concrete and would allow other folks who use BBCode+reprex (are there dozens of you? 😁) to install and try.*

**Comment by mcanouil** [comment]
> I'm not sure yet if I'm willing to support a BBCode `venue`. It seems a bit niche, but it also looks like a very modest amount of code gets the job done (thanks for showing that). So I'll let this age.

I am using BBCode in only one place, a French R forum based on phpbb, so a "niche" would probably be an euphemism 😅.

> _Maybe you want to express your proposal as a PR? That makes it even more concrete and would allow other folks who use BBCode+reprex (are there dozens of you? 😁) to install and try._

I'll improve the ~~hack~~ code at some point and will make a PR (after v1.0.0 is released 🙃).
