### ISSUE TITLE
Remove outdated link from further reading?

### ISSUE THREAD

**Issue by maelle** [tidyverse/reprex#352]
In https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html there's "How to write a reproducible example from Hadley Wickham’s Advanced R book"

* it's from the first version where there's only an alert about the new edition from the homepage (that's actually not the right link?)
* in the second edition it seems readers are directed to... reprex :grin:

**Comment by jennybc** [comment]
Good idea!

Closed in 1653a81c7b6b755b9e8c2e88fd78068ef3f1ef56
