### ISSUE TITLE
Reprex fails with a missing `c()`

### ISSUE THREAD

**Issue by oharac** [tidyverse/reprex#359]
Hi,

A student found that she was unable to render a reprex for code similar to this (note the missing `c` in front of the `('Adelie', 'Gentoo')`:
```
library(tidyverse)
library(palmerpenguins)

penguins %>%
  filter(species %in% ('Adelie', 'Gentoo'))
```
starts but ultimately fails to render reprex:
```
ℹ Rendering reprex...
Error in parse(text = x, keep.source = TRUE) : 
  <text>:10:32: unexpected ','
9: penguins %>%
10:   filter(species %in% ('Adelie',
                                   ^
```
Maybe capturing this type of parsing error is beyond the scope of the package, but I was surprised to see an easy typo cause `reprex` to fail.  Thanks!

**Comment by jennybc** [comment]
This is an error bubbling up from knitr / rmarkdown. This code cannot be parsed. So there's nothing really that reprex can do, as it is just a wrapper around knitr / rmarkdown.

FWIW, when I reproduced this with a plain `.Rmd`, in RStudio, I see a very clear indication of the syntax problem. Students would be well-served by letting RStudio show such diagnostics and to keep an eye out for big red X's.

<img width="583" alt="Screen Shot 2021-02-11 at 6 40 32 PM" src="https://user-images.githubusercontent.com/599454/107724496-d471f900-6c98-11eb-99b6-d1207e632131.png">
