### ISSUE TITLE
Reprex does not consult the current selection on RStudio Cloud

### ISSUE THREAD

**Issue by 23ava** [tidyverse/reprex#369]
I would like to use reprex on RStudio Cloud

The `reprex` manual says:

> When the clipboard is structurally unavailable, e.g., on RStudio
> Server or RStudio Cloud, reprex() consults the current selection
> instead of the clipboard

However, when I select my code in the script on RStudio Cloud and type `reprex::reprex()` in the console I get the following message:

    No user-supplied code found … so we’ve made some up. You’re welcome!
    
    ``` r
    sprintf("Happy %s!", weekdays(Sys.Date()))
    #> [1] "Happy Thursday!"
    ```
    
    <sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I get following error in the console if I copy the code into the clipboard and/or select it the script:

```
    > reprex::reprex()

    ! No input provided and clipboard is not available.
```

``` `reprex({rnorm(10)])` ``` works

I originally posted this question [here](https://stackoverflow.com/posts/66695915/edit)

Thank you for your help!

**Comment by jennybc** [comment]
This is a feature of *dev* reprex, so it is not yet on CRAN. Therefore, I suspect this is a version issue. (The pkgdown site reflects dev capabilities.)

I will release these features to CRAN reprex soon.
