### ISSUE TITLE
Add venue/style for bugzilla

### ISSUE THREAD

**Issue by llrs** [tidyverse/reprex#370]
Reprex doesn't seem to work out of the box with bugzilla. See this [issue](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=18081). 

So there's no need to have ` ```r` just ` ``` ` works well, and also the html sup is not recongized, but perhaps it could be changed to a note in markdown style. 

I have a package that would like to use reprex to submit R code to issues on bugzilla: [bugRzilla](https:github.com/llrs/bugRzilla). This could come handy. Thanks!

**Comment by mcanouil** [comment]
Is it not, what `venue = "slack"` does?

``` r
(reprex(input = c("#' Hello world", "## comment", "1:5"), venue = "slack"))
#> i Rendering reprex...
#> v Reprex output is on the clipboard.
#> [1] "Hello world"      ""                 "```"              "## comment"       "1:5"             
#> [6] "#> [1] 1 2 3 4 5" "```"   
```

**Comment by llrs** [comment]
Oh, sorry didn't know that slack mean just markdown syntax. Also nice that using `#'` one can set the text (and titles) for reprex. Many thanks
