### ISSUE TITLE
How to reprex a ggvis? Gives: "Error: This reprex appears to crash R"

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/reprex#371]
I am not able to produce a reprex containing a `ggvis` plot, giving error: _Error: This reprex appears to crash R_. Using `std_out_err = TRUE` says further:

> Error : Functions that produce HTML output found in document targeting commonmark output.
> Please change the output type of this document to HTML. Alternatively, you can allow
> HTML output in non-HTML formats by adding this option to the YAML front-matter of
> your rmarkdown file:
>   always_allow_html: true
> Note however that the HTML output will not be visible in non-HTML formats.

I assume this is because it is an interactive/shiny-based plot? But still, I was hoping there is a simple workaround to inlude a ggvis in a reprex? Thanks!!

Reproducible code:

```
library(ggvis)

mtcars %>% 
  ggvis(~wt, ~mpg) %>% 
  layer_points()

reprex::reprex(std_out_err = TRUE)
```

**Comment by jennybc** [comment]
Yeah, I'm afraid this is never going to work / can't work. A sample of similar issues:

#78
#185
#317
