### ISSUE TITLE
Reprex not rendering every gganimate animation 

### ISSUE THREAD

**Issue by py9mrg** [tidyverse/reprex#374]
Hello,

When trying to render a reprex containing multiple gganimate animations, I found that reprex would only produce the final animation so I had to do each one separately and manually stitch them together afterwards. See https://github.com/thomasp85/gganimate/issues/438 specifically but I'll do a simpler version here, only the second animation, `anim2`, will be produced by reprex::reprex() below...

``` r
library(gganimate)
#> Loading required package: ggplot2

data <- tibble::tibble(dates = seq(as.Date("2021-01-01"), as.Date("2022-12-31"), by = 1),
                       x = rep(seq(as.Date("2021-01-01"), as.Date("2021-12-31"), by = 1), 2),
                       y = as.numeric(1:730),
                       type = c(rep("A", 365), rep("B", 365)))

# notice colours of lines start wrong and flicker
p <- ggplot(data, aes(x = x, y = y, colour = type, group = type)) +
  geom_path()

anim <- p +
  transition_reveal(dates)
anim

# similar but more pronounced when manually specifying colours - not even a solid line at first
p2 <- ggplot(data, aes(x = x, y = y, colour = type, group = type)) +
  geom_path() +
  scale_colour_manual(values = c("grey", "red"))

anim2 <- p2 +
  transition_reveal(dates)
anim2
```

![](https://i.imgur.com/6CFYReE.gif)

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jennybc** [comment]
Yeah, I'm afraid this is never going to work / can't work. A sample of similar issues:

#78
#185
#317
# 371

for understand why.

**Comment by jennybc** [comment]
I may have closed this too soon, as I see that one gif does show up. Yet I still don't see how reprex is the problem 🤔

**Comment by py9mrg** [comment]
No worries - I can't either, and it's entirely possible it's my fault. I seem to have broken both gganimate *and* reprex with my example!

**Comment by jennybc** [comment]
Having given it very little thought, I do wonder if the individual gifs are overwriting each other? Maybe it's a file naming issue?
