### ISSUE TITLE
Feature request: overload library() to print user's package version

### ISSUE THREAD

**Issue by pnacht** [tidyverse/reprex#376]
When users post a reprex, an immediate question is often "what version are you using of package X"? For this reason, I often post my reprexes starting with `packageVersion()` calls.

This line of questioning can be eliminated altogether by running the reprex in an environment where `library()` and `require()` have been overwritten with something simple, such as:

``` r
library <- function(x) {
    x <- as.character(substitute(x))
    message(x, " version ", packageVersion(x))
    base::library(x, character.only = TRUE)
}

suppressPackageStartupMessages({
    library(dplyr)
    library(plotly)
})
#> dplyr version 1.0.5
#> plotly version 4.9.3

# showing the packages are actually loaded
data.frame(a = 1) %>% mutate(b = 2)
#>   a b
#> 1 1 2
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jennybc** [comment]
reprex doesn't do anything this invasive and I am reluctant to do so.

The official solution to this is to use the `session_info` argument to include package versions (nicely tucked away in a collapsible details tag, in venues where that's supported). For a much more surgical approach to revealing package version, I think, as you say, an explicit call to `packageVersion()` is a good solution.
