### ISSUE TITLE
Update rlang options for backtraces

### ISSUE THREAD

**Issue by lionel-** [tidyverse/reprex#377]
Following these changes:

- https://github.com/r-lib/rlang/pull/1215
- https://github.com/r-lib/rlang/commit/10331f87

The only rlang option that needs to be set once the next version of rlang is on CRAN is:

```r
options(rlang_backtrace_on_error = "full")
```

The other options `rlang_trace_top_env` and `rlang:::force_unhandled_error` may be removed.

**Comment by jennybc** [comment]
Note: at the time of writing rlang is at 0.4.11.9000.

**Comment by romainfrancois** [comment]
Not specifically about backtraces, but having rlang errors print with their causes would be useful: 

``` r
library(dplyr, warn.conflicts = FALSE)
# pak::pak("r-lib/rlang")
library(rlang)

f <- function() {
  abort("Error from f()")
}

g <- function() {
  withCallingHandlers(f(), error = function(cnd) {
    abort("Error from g()", parent = cnd)
  })
}
g()
#> Error: Error from g()
```

<sup>Created on 2021-10-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

whereas I see this on the console, with the "Caused by:" ...

![image](https://user-images.githubusercontent.com/2625526/136045285-51c1f051-eb95-49c1-a838-e14e0cbd2bdf.png)

**Comment by lionel-** [comment]
yup we need a customisation point in knitr for that, this is on my radar.

**Comment by jennybc** [comment]
Is it time to revisit what reprex should be doing? Now than rlang 1.0.0 is, indeed, out.

**Comment by lionel-** [comment]
oh yes, these options need to be updated: https://github.com/tidyverse/reprex/blob/ed8972e24b70532ea78ec14bc70a6fe673f0807b/R/reprex_document.R#L136-L138

You now only need to set:

```r
options(
  rlang_backtrace_on_error_report = "full"
)
```

The documentation for backtrace display in knitr documents is at https://rlang.r-lib.org/reference/rlang_backtrace_on_error.html#errors-in-rmarkdown
