### ISSUE TITLE
R chunks are added to original Rmarkdown files

### ISSUE THREAD

**Issue by randy3k** [tidyverse/reprex#378]
I just notice that rendering a Rmarkdown file with output `reprex_doucment` would modify the file in place. To demonstrate it, consider

```sh
echo "---\noutput: reprex::reprex_document\n---" > /tmp/test.Rmd
Rscript --quiet -e "rmarkdown::render('/tmp/test.Rmd', quiet = TRUE)"
cat /tmp/test.Rmd
rm /tmp/test.Rmd
```

Some R chunks are added to the original document. Additionally, an advertisement is also added to the original file.
    
    ```{r reprex-options, include = FALSE}
    options(
      keep.source = TRUE,
      rlang_trace_top_env = globalenv(),
      `rlang:::force_unhandled_error` = TRUE,
      rlang_backtrace_on_error = "full",
      crayon.enabled = FALSE,
      reprex.current_venue = "gh"
    )
    ```
    
    ```{r, results = 'asis', echo = FALSE, include = file.exists('.Rprofile'), eval = file.exists('.Rprofile')}
    cat(sprintf("*Local `.Rprofile` detected at `%s`*", normalizePath(".Rprofile")))
    ```
    
    ---
    output: reprex::reprex_document
    ---
    
    <sup>Created on `r Sys.Date()` by the [reprex package](https://reprex.tidyverse.org) (v`r utils::packageVersion("reprex")`)</sup>

# System information

R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

With all the latest `reprex`, `knitr` and `rmarkdown`.

**Comment by jennybc** [comment]
Yeah, I would basically describe what happens in this scenario as "undefined behaviour". The `reprex_document` output format is not designed for general, arbitrary use. It is definitely designed to be used with `reprex_render()`, almost certainly via `reprex()`.

As it says in the docs (bold mine):

> Both (templates) include `knit: reprex::reprex_render` in the YAML, which causes the RStudio "Knit" button to use `reprex_render()`. **If you render these documents yourself, you should do same.**

Arguments like `advertise` and `session_info` are described like so (bold mine):

> Add content to the **primary input**, prior to rendering

So if you choose to use reprex's output format outside of the reprex package, at this point I'm doing to say it's up to you to work around these aspects.
