### ISSUE TITLE
Reprex: How to used in Shiny R 

### ISSUE THREAD

**Issue by jyotikant** [tidyverse/reprex#382]
I want to copy the more than two column values in one dropdown list.  I am not able to solve my problem using this. can you help me?

only I want to add two column values in input id "BP1", "BP2"
selectizeGroupUI(
BPName = list(inputId = "BP1","BP2", title = "Select The Name of BP")
)
![image](https://user-images.githubusercontent.com/7898754/125041529-7bc35280-e0b6-11eb-80e6-049a6e165c1b.png)
@hadley @cwickham

**Comment by jennybc** [comment]
Hi @jyotikant,

This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio Community](https://community.rstudio.com). 

Thanks!
