### ISSUE TITLE
Parse error when braces are on a separate line

### ISSUE THREAD

**Issue by billdenney** [tidyverse/reprex#386]
When braces are on a separate line (see the `suppressWarnings()` difference where braces are on the same line vs. different lines at the top), reprex can generate a parse error:

The first example fails to parse with the error:

```
i Rendering reprex...
Error in parse(text = x, keep.source = TRUE) : 
  <text>:11:3: unexpected symbol
10:   rlang::warn("show this")
11:   rlang
      ^
```

```r
reprex::reprex({
rlang::warn("show this")
rlang::warn("hide this", class="hider")

suppressWarnings(
{
  rlang::warn("show this")
  rlang::warn("hide this", class="hider")
},
classes="hider")
})
```

The second example where the { is on the same line as `suppressWarnings(` succeeds:

``` r
rlang::warn("show this")
#> Warning: show this
rlang::warn("hide this", class="hider")
#> Warning: hide this

suppressWarnings({
  rlang::warn("show this")
  rlang::warn("hide this", class="hider")
},
classes="hider")
#> Warning: show this
```

<sup>Created on 2021-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jennybc** [comment]
I just successfully ran the first example, so I'm going to cautiously celebrate that this has somehow been fixed by other changes in reprex or packages we use :crossed_fingers:

It seems to basically be the same as #412, so this seems plausible.
