### ISSUE TITLE
Error for dirname receiving a non-character input on reperx that nearly crashes R

### ISSUE THREAD

**Issue by billdenney** [tidyverse/reprex#388]
When trying to replicate a base R bug (https://bugs.r-project.org/show_bug.cgi?id=16441), I wanted to give a reprex for it.  When trying to generate the reprex, there was an error in reprex.

``` r
reprex::reprex({
e <- new.env()
attr(e, "e") <- e
object.size(e)
})
```

That resulted in the following output on the R console.

```
i Rendering reprex...
Error in dirname(path[!is_missing]) : 
  a character vector argument expected
```

This is with R 4.1.0 on Windows 10.

**Comment by billdenney** [comment]
The error appears to be that `out` is `NULL` here, and that appears to be a unique output that is crashing R.

https://github.com/tidyverse/reprex/blob/945d63dedde31b11902c316641a230f851e11ed9/R/reprex_render.R#L94-L111

**Comment by jennybc** [comment]
The root problem is that this error (`C stack usage ... is too close to the limit`) causes the rendering to stop.

For some reason, the error caught in reprex is `NULL`, which I was not expecting, which lead to us trying to proceed with a non-existent path.

I think the only thing I can do in reprex is to throw a marginally more informative error.

It is interesting to ask what's special about this error and whether some other package (evaluate? knitr?) or R itself could do something differently to allow it to be knit.

If I surround the tricky code with `tryCatch()`, it **can** be reprexed:

``` r
e <- new.env()
attr(e, "e") <- e
blah <- tryCatch(
  object.size(e),
  error = function(e) e
)
blah
#> <simpleError: C stack usage  7969228 is too close to the limit>
str(blah)
#> List of 2
#>  $ message: chr "C stack usage  7969228 is too close to the limit"
#>  $ call   : NULL
#>  - attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

cc @cderv

**Comment by cderv** [comment]
Thanks Jenny for the ping. It seems this error (type of error) is not catched the same as other by **evaluate**

````
> evaluate::evaluate("stop('a')")
[[1]]
$src
[1] "stop('a')"

attr(,"class")
[1] "source"

[[2]]
<simpleError in eval(expr, envir, enclos): a>

> evaluate::evaluate('e <- new.env()
+                    attr(e, "e") <- e
+                    object.size(e)')
Error: C stack usage  15922884 is too close to the limit
````

So we should indeed look there.
