### ISSUE TITLE
reprex() writes to clipboard with a wrong encoding on Windows with R-devel

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/reprex#406]
Sorry, I know this is a problem on clipr's side, but let me file this here just in case I fail to get this fixed before the release of R 4.2.0....

#### Code:

``` r
reprex::reprex({
"あ"
})
```

#### On viewer pane of RStudio:

![image](https://user-images.githubusercontent.com/1978793/151791818-041ee1a2-2bde-469d-b7c6-3ce655a10f82.png)

#### In my clipboard:

````
``` r
"縺・
#> [1] "縺・
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
````

**Comment by jennybc** [comment]
Do we think the clipr update means reprex will be OK once r-devel becomes r-release? That's my interpretation of events. I.e. this is safe to close?

**Comment by yutannihilation** [comment]
Yes! Sorry I forgot to close this.
