### ISSUE TITLE
Support GitHub light/dark themes

### ISSUE THREAD

**Issue by davidchall** [tidyverse/reprex#417]
GitHub today [announced](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) the beta feature to display 1 of 2 uploaded images based on theme context.

This is a really cool feature and I immediately thought of reprex! 😄 I'm thinking reprex could render ggplot diagrams with light and dark themes and upload both images with this new syntax.

Not at all urgent of course - I just thought this was a neat idea.

**Comment by jennybc** [comment]
I don't see a particularly appealing way to work this idea into the existing, pretty minimalistic reprex workflow. I'm glad to have learned about it, though, and will file it away as something to think about in case circumstances change.
