### ISSUE TITLE
Take advantage of some backtrace improvements

### ISSUE THREAD

**Issue by jennybc** [tidyverse/reprex#433]
Details in https://github.com/r-lib/rlang/pull/1557, which would need to be merged and released first.

https://github.com/tidyverse/reprex/blob/77ec1f612ea3d94534d6b37336a45f2d2957f3b2/R/reprex_document.R#L136-L141

should look more like

``` r
rlang::global_entrace()
options(
  keep.source = TRUE,
  rlang_backtrace_on_error_report = "full",
  rlang_backtrace_on_warning_report = "full"
  crayon.enabled = FALSE,
  reprex.current_venue = "{venue}"
)
```

**Comment by lionel-** [comment]
This would also close #230.

**Comment by jennybc** [comment]
The relevant rlang PR has been merged, but not yet released.

**Comment by krlmlr** [comment]
Now in rlang 1.1.0.
