### ISSUE TITLE
Add wd panel to Rstudio Addins Menu

### ISSUE THREAD

**Issue by agila5** [tidyverse/reprex#439]
Dear package maintainers,  I decided to create this issue since I would like to make a case for adding a new panel to the reprex_addin menu where a user can specify the `wd` for the reprex. 

In particular, I typically use the `reprex` package to create reproducible examples which also involve external files that must be read into the R session. IMO, it is pretty annoying that every time I make a reprex from the add-in UI, I need to manually redefine the path of all external files specifying the full path (i.e. C:\...) instead of the relative path (according to the .Rproj folder). Is there an alternative way to run the reprex from the UI and set the wd? 

Would you be interested in reviewing a PR?

**Comment by hadley** [comment]
One of the goals of the reprex is to produce code that can be used by others, and obviously referring to external data that only exists on your computer doesn't help achieve that. For that reason, I don't think this is a good fit for the reprex package. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
