### ISSUE TITLE
Error in `reprex_render_impl()`

### ISSUE THREAD

**Issue by SimaSohrabi** [tidyverse/reprex#440]
Please briefly describe your problem and what output you expect. If
you have a question, please don't use this form. Instead, ask on
<https://community.rstudio.com/> or <https://stackoverflow.com/>.

---

Error in `reprex_render_impl()`:

```r
Backtrace:
    x
 1. \-reprex::reprex()
 2.   \-reprex:::reprex_impl(...)
 3.     \-reprex:::reprex_render_impl(r_file, new_session = new_session, html_preview = html_preview)
 4.       \-cli::cli_abort(...)
 5.         \-rlang::abort(...)
```

**Comment by sjackson1997** [comment]
I am getting the same error when I try to run reprex()

```
> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `reprex_render_impl()`:
! Unhandled error from `rmarkdown::render()` in the external process.
ℹ This is an internal error that was detected in the reprex package.
  Please report it at <https://github.com/tidyverse/reprex/issues> with a reprex and the full backtrace.
---
Backtrace:
    ▆
 1. └─reprex::reprex(input = "C:/Users/...<removed>...quasiquotation.R")
 2.   └─reprex:::reprex_impl(...)
 3.     └─reprex:::reprex_render_impl(r_file, new_session = new_session, html_preview = html_preview)
 4.       └─cli::cli_abort(...)
 5.         └─rlang::abort(...)
 ```

**Comment by hadley** [comment]
Can you please provide a bit more context about exactly what you're doing when you see the error?

**Comment by jennybc** [comment]
We can't act on these reports until someone provides the code they were trying run reprex on. Hopefully someone will return with more detail.

**Comment by Luccan97** [comment]
A colleague encountered the same error, and it was resolved by installing the processx package:

`install.packages("processx")`

After installing processx and restarting R, reprex worked normally.
