### ISSUE TITLE
Question: Does `{reprex}` support MS Teams?

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/reprex#446]
I am trying to paste into MS Teams chat but to no avail. Is there a workaround?

**Comment by jennybc** [comment]
Can you elaborate on "to no avail"? Is there anything on your clipboard? Or, there is, but it is somehow rejected for paste by Teams?

**Comment by ramiromagno** [comment]
Hi Jenny,

Sorry for my bad manners! It does copy to the clipboard fine, it's just that it won't get nicely formatted automatically. I am guessing this is an issue with MS Teams rather than reprex... see https://stackoverflow.com/questions/55014770/how-can-i-paste-markdown-in-microsoft-teams.
