### ISSUE TITLE
Warning exists when `reprex(... style = FALSE)`

### ISSUE THREAD

**Issue by beauchamplab** [tidyverse/reprex#461]
With `style=FALSE`, users would like to render without `styler`. I wonder if "Install the styler package" should still show up?

``` r
reprex::reprex({ print("") }, style = FALSE)
#> ✖ Install the styler package in order to use `style = TRUE`.
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> ℹ Rendering reprex...
```

<sup>Created on 2024-02-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
Yeah this appears to be a thinko in this helper. It doesn't seem to consult whether `style` is `TRUE` or `FALSE` 🙈

https://github.com/tidyverse/reprex/blob/e1f65e9949ed30d1ee4f1e984736b408d8e001ee/R/reprex_impl.R#L129-L137

**Comment by beauchamplab** [comment]
Our users asked us if they should install `styler` since they got this "warning". Maybe:

``` r
style_requires_styler <- function(style) { 
   if (style && !requireNamespace("styler", quietly = TRUE)) { 
     reprex_danger(" 
       Install the {.pkg styler} package in order to use 
       {.code style = TRUE}.") 
     style <- FALSE 
   } 
   invisible(style) 
 } 
```
?

**Comment by jennybc** [comment]
Yes LGTM. Would you like to make a PR?
