### ISSUE TITLE
Advertise reprex

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/reprex#69]
Have you considered inserting a comment `# Created on ${date} using the reprex package` at the top or the bottom of the output? Both as a quality indicator and a hint to users who don't know the package yet.

**Comment by hadley** [comment]
I like this idea too.

**Comment by jennybc** [comment]
@krlmlr Is this what you had in mind? Here's the output of `reprex(mean(rnorm(3)))` under the above PR:

---

``` r
mean(rnorm(3))
#> [1] -0.6492532
```

``` r
reprex::reprex_info()
#> Created on Tue Oct 10 23:00:27 2017 with the reprex package
```

---

This might look a little silly -- why not just include the output? It's not easy to get knitr to format this chunk like the others if it includes no code, e.g. if `echo = FALSE`. Hence the `reprex_info()` function.

I can't decide if `advertise` should default to `TRUE` or `FALSE` 🤔

**Comment by hadley** [comment]
Maybe put it at the top? So it's more easily skimmed past? Use ISO8601? 😉 

```R
reprex::reprex_info()
#> Created by the reprex package; 2017-10-10

mean(rnorm(3))
#> [1] -0.6492532
```

I think it makes sense to include by default. It only adds 3 lines, is easily deleted if you don't want it, and provides useful information.

**Comment by jennybc** [comment]
OK @hadley how's this? Use of `echo` at all is detrimental to GFM, so I moved the ad into prose, to the top, and ISO8601'd it.

Output of `reprex(mean(rnorm(3)))`:

---

Created by the reprex package; 2017-10-11

``` r
mean(rnorm(3))
#> [1] 0.3626104
```

**Comment by jennybc** [comment]
Or I could stick it at the top of the body, i.e. do *exactly* what you have above.

Alternative output of `reprex(mean(rnorm(3)))`:

---

``` r
reprex::reprex_info()
#> Created by the reprex package; 2017-10-11

mean(rnorm(3))
#> [1] -1.212095
```

**Comment by hadley** [comment]
I think I still prefer the second form. Maybe also include reprex's version number?

**Comment by jennybc** [comment]
OK here's where we ended up. `reprex(mean(rnorm(3)))` yields this:

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-10-12

mean(rnorm(3))
#> [1] -0.02475685
```

**Comment by jennybc** [comment]
Summarizing recent ideas from Slack convo:

  * Move to bottom?
  * Find a way to include the info from `reprex::reprex_info()` but not the code. Details tag? Generate prose for a Markdown link, e.g., `Created by the [reprex package](https://cran.r-project.org/package=reprex)`.
  * Put date in front of package version (not all agree on this): `Run on 2017-11-06 with reprex (v0.1.1.900)`
