### ISSUE TITLE
Suppress package message argument

### ISSUE THREAD

**Issue by hadley** [tidyverse/reprex#70]
Defaulting to true, since _usually_ it's not germane to the problem

**Comment by krlmlr** [comment]
Does this require computing on the language, e.g., find and transform all `library()` calls?

In a similar vein, I tend to forget to load "magrittr" in my reprexes (because I have it in `.Rprofile`), it would be great if reprex could detect pipe usage and fix the code for me.

**Comment by hadley** [comment]
You could either either use a hack to bind a session-wide `packageStartupMessage` handler, or provide a shim for `library()`

**Comment by jennybc** [comment]
A lower tech solution is to insert extra chunk headers before and after every run of `library()` calls. If I do that by hand, it already work with the current package:

Input:

```r
#+ message = FALSE
library(tidyverse)
message("1 can you hear me now?")

#+ body
as_tibble(iris)
message("2 can you hear me now?")
```

Output:
``` r
library(tidyverse)
message("1 can you hear me now?")
```

``` r
as_tibble(iris)
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>  <fctr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
message("2 can you hear me now?")
#> 2 can you hear me now?
```

**Comment by krlmlr** [comment]
Maybe just add a `library` argument to `reprex()`, defaulting to some option? (This package is mostly for interactive use, an option seems okay to me.)

**Comment by jennybc** [comment]
> it would be great if reprex could detect pipe usage and fix the code for me.

What fix do you have in mind here? Maybe insert

```
`%>%` <- magrittr::`%>%`
```

whenever the pipe is found in the source? But so many packages re-export it and this wouldn't be necessary. Or do you mean deploy the fix iff the reprex fails?

**Comment by krlmlr** [comment]
Yes, or `library(magrittr)`. But I don't want to overthink this.

I'd find it easier to write `reprex(library = "magrittr")` for some one-liner I've copied to the clipboard, than starting a new text file and typing the `library()` call myself, then copying the contents and then calling `reprex()`.

**Comment by krlmlr** [comment]
Maybe surround the whole `knit()` call with `suppressPackageStartupMessages()` (or an equivalent?)

**Comment by jennybc** [comment]
To what extent are we trying to suppress the tidyverse startup message vs startup messages in general? Because if it's focused on the tidyverse, we just toggle this option in the template:

https://github.com/tidyverse/tidyverse/blame/c13baecbe13f9d99054f424da1bc39952ceca360/NEWS.md#L3-L4

**Comment by jennybc** [comment]
I have solved the specific problem of suppressing the tidy verse startup message. I'm going to close this and see if we truly feel the need for more general mechanism.

Opened a separate issue re: the pipe: #106.
