### ISSUE TITLE
Adding traceback() info

### ISSUE THREAD

**Issue by HeidiSeibold** [tidyverse/reprex#74]
I asked a question about whether to add traceback-output during the [ROpenSci community call](https://ropensci.org/blog/blog/2017/02/17/comm-call-v13) and @jennybc asked me to open an issue. So here it is :cake: 

What I imagine could look like the sessionInfo() tab, that one can open if they want to.
I.e. something like `reprex::reprex(rnorm(10), venue = "gh", si = TRUE, tb = TRUE)` where additionally to the session-info-tab there will also appear a traceback-tab.

The question came to me because I was asked to add the traceback in an issue I recently opened: https://github.com/mlr-org/mlr/issues/1490

**Comment by hadley** [comment]
I think reprex should probably add the `traceback()` by default by using a custom error handler

**Comment by hadley** [comment]
Actually this is more challenging than I thought because reprex uses rmarkdown/knitr, which eats errors in an internal `tryCatch()`.

**Comment by wlandau** [comment]
For what it's worth, I have started using `evaluate::try_capture_stack()` as a temporary workaround.

``` r
code <- quote(identity(stop("msg")))
env <- environment()
error <- evaluate::try_capture_stack(code, env)
error$message
#> [1] "msg"
error$call
#> identity(stop("msg"))
error$calls
#> [[1]]
#> identity(stop("msg"))
#> 
#> [[2]]
#> stop("msg")
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
I suspect the long-term solution to this is going to be #230 Entrace base errors?

**Comment by jennybc** [comment]
Closing with the rationale that #230 represents the improvements needed.
