### ISSUE TITLE
reprex renders data.frame wrong?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/reprex#77]
I'm not sure if this is a bug with the way I am using reprex, but when I try to copy and paste this code two odd things occur:
1. When I copy and paste the code onto github, it seems like there are slashes that are put into my column headers, which seems like a bug:
2. Secondly, it seems like there is a bit of a spacing issue, which makes the table not renderable on github:
Code below:
#Sample Dataframe
pacman::p_load(magrittr,dplyr,formattable)
sample = data.frame(
  beer_brewerId = c("8481", "8481", "8481"),
  rev_app = c("4","1", "2"),
  beer_name = c("John Harvards Simcoe IPA", "John Harvards Simcoe IPA", "John Harvards American Brown Ale"),
  review_taste =c("6", "7", "6"), stringsAsFactors = FALSE
)
glimpse(sample)
formattable(sample, align ="c")

#Piping:
sample %>%
  filter(beer_name == "John Harvards Simcoe IPA") %>%
  formattable(., align = "c")

# **Output from reprex() function:**
``` r
#Sample Dataframe
pacman::p_load(magrittr,dplyr,formattable)
sample = data.frame(
  beer_brewerId = c("8481", "8481", "8481"),
  rev_app = c("4","1", "2"),
  beer_name = c("John Harvards Simcoe IPA", "John Harvards Simcoe IPA", "John Harvards American Brown Ale"),
  review_taste =c("6", "7", "6"), stringsAsFactors = FALSE
)
glimpse(sample)
#> Observations: 3
#> Variables: 4
#> $ beer_brewerId <chr> "8481", "8481", "8481"
#> $ rev_app       <chr> "4", "1", "2"
#> $ beer_name     <chr> "John Harvards Simcoe IPA", "John Harvards Simco...
#> $ review_taste  <chr> "6", "7", "6"
formattable(sample, align ="c")
```

<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:center;">
beer\_brewerId
</th>
<th style="text-align:center;">
rev\_app
</th>
<th style="text-align:center;">
beer\_name
</th>
<th style="text-align:center;">
review\_taste
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
John Harvards American Brown Ale
</td>
<td style="text-align:center;">
6
</td>
</tr>
</tbody>
</table>
``` r

#Piping:
sample %>%
  filter(beer_name == "John Harvards Simcoe IPA") %>%
  formattable(., align = "c")
```

<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:center;">
beer\_brewerId
</th>
<th style="text-align:center;">
rev\_app
</th>
<th style="text-align:center;">
beer\_name
</th>
<th style="text-align:center;">
review\_taste
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
7
</td>
</tr>
</tbody>
</table>

**Comment by pgensler** [comment]
I believe the reprex function is inserting an extra line break between the code and the HTML rendered. I have attached the screenshot with the tables having extra /'s in the HTML, and what code is throwing the error.
![needs-space](https://cloud.githubusercontent.com/assets/7308115/24572876/5f0d7b36-1642-11e7-9f8f-eafad5d5639e.jpg)
![bad-cols-headers](https://cloud.githubusercontent.com/assets/7308115/24572877/5f0e0d94-1642-11e7-968b-5dc8d26a7ffa.jpg)


# The correct output should be as such::

``` r
#Sample Dataframe
pacman::p_load(magrittr,dplyr,formattable)
sample = data.frame(
  beer_brewerId = c("8481", "8481", "8481"),
  rev_app = c("4","1", "2"),
  beer_name = c("John Harvards Simcoe IPA", "John Harvards Simcoe IPA", "John Harvards American Brown Ale"),
  review_taste =c("6", "7", "6"), stringsAsFactors = FALSE
)
glimpse(sample)
#> Observations: 3
#> Variables: 4
#> $ beer_brewerId <chr> "8481", "8481", "8481"
#> $ rev_app       <chr> "4", "1", "2"
#> $ beer_name     <chr> "John Harvards Simcoe IPA", "John Harvards Simco...
#> $ review_taste  <chr> "6", "7", "6"
formattable(sample, align ="c")
```

<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:center;">
beer_brewerId
</th>
<th style="text-align:center;">
rev_app
</th>
<th style="text-align:center;">
beer_name
</th>
<th style="text-align:center;">
review_taste
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
John Harvards American Brown Ale
</td>
<td style="text-align:center;">
6
</td>
</tr>
</tbody>
</table>

``` r
#Piping:
sample %>%
  filter(beer_name == "John Harvards Simcoe IPA") %>%
  formattable(., align = "c")
```
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:center;">
beer_brewerId
</th>
<th style="text-align:center;">
rev_app
</th>
<th style="text-align:center;">
beer_name
</th>
<th style="text-align:center;">
review_taste
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
8481
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
John Harvards Simcoe IPA
</td>
<td style="text-align:center;">
7
</td>
</tr>
</tbody>
</table>

**Comment by pgensler** [comment]
attaching rstudio viewerpane for verification:
![rstudio-viewer](https://cloud.githubusercontent.com/assets/7308115/24572964/3cf2525a-1643-11e7-8320-d5bcb6d380c9.jpg)

**Comment by yutannihilation** [comment]
You should file this issue to formattable as this is not a reprex's fault. I could reproduce this issue by knitting a simple Rmd: https://gist.github.com/yutannihilation/0108dbde9e7db99ca8f670586c083aa5#file-test-rmd

Markdown spec says:

> An HTML block is a group of lines that is treated as raw HTML (and will not be escaped in HTML output).
http://spec.commonmark.org/0.26/#html-blocks

So, we don't need this `\` for escape here, whereas formattable (or htmlwidgets? I'm not sure...) mistakenly add the escape.

**Comment by hadley** [comment]
Could you please construct a simpler reprex? For your case this would include loading packages in a standard way, eliminating unneeded packages (magrittr + dplyr) and simplifying the data frame.

**Comment by jennybc** [comment]
An important aspect of this is the HTML output of formattable, so the title is a bit misleading. If I save this reprex as `.R` with this yaml:

```yaml
#' ---
#' output: github_document
#' ---
```

And render it with rmarkdown directly, the `.md` has the same "features", e.g. the escaped underscores in the variable names and the lack of space between the html table and the next R chunk. Ditto if I store this code in `.Rmd`.

So I think this is really about how `rmarkdown::render()` works when output format is `github_document` and a chunk creates html.

**Comment by jennybc** [comment]
I think I have the fix. With it, the original code (modified to not use pacman) produces this output:

``` r
#Sample Dataframe
library(magrittr)
suppressPackageStartupMessages(library(dplyr))
library(formattable)

sample = data.frame(
  beer_brewerId = c("8481", "8481", "8481"),
  rev_app = c("4","1", "2"),
  beer_name = c("John Harvards Simcoe IPA", "John Harvards Simcoe IPA", "John Harvards American Brown Ale"),
  review_taste =c("6", "7", "6"), stringsAsFactors = FALSE
)
glimpse(sample)
#> Observations: 3
#> Variables: 4
#> $ beer_brewerId <chr> "8481", "8481", "8481"
#> $ rev_app       <chr> "4", "1", "2"
#> $ beer_name     <chr> "John Harvards Simcoe IPA", "John Harvards Simco...
#> $ review_taste  <chr> "6", "7", "6"
formattable(sample, align ="c")
```

<table class="table table-condensed">

<thead>

<tr>

<th style="text-align:center;">

beer\_brewerId

</th>

<th style="text-align:center;">

rev\_app

</th>

<th style="text-align:center;">

beer\_name

</th>

<th style="text-align:center;">

review\_taste

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:center;">

8481

</td>

<td style="text-align:center;">

4

</td>

<td style="text-align:center;">

John Harvards Simcoe IPA

</td>

<td style="text-align:center;">

6

</td>

</tr>

<tr>

<td style="text-align:center;">

8481

</td>

<td style="text-align:center;">

1

</td>

<td style="text-align:center;">

John Harvards Simcoe IPA

</td>

<td style="text-align:center;">

7

</td>

</tr>

<tr>

<td style="text-align:center;">

8481

</td>

<td style="text-align:center;">

2

</td>

<td style="text-align:center;">

John Harvards American Brown Ale

</td>

<td style="text-align:center;">

6

</td>

</tr>

</tbody>

</table>

``` r

#Piping:
sample %>%
  filter(beer_name == "John Harvards Simcoe IPA") %>%
  formattable(., align = "c")
```

<table class="table table-condensed">

<thead>

<tr>

<th style="text-align:center;">

beer\_brewerId

</th>

<th style="text-align:center;">

rev\_app

</th>

<th style="text-align:center;">

beer\_name

</th>

<th style="text-align:center;">

review\_taste

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:center;">

8481

</td>

<td style="text-align:center;">

4

</td>

<td style="text-align:center;">

John Harvards Simcoe IPA

</td>

<td style="text-align:center;">

6

</td>

</tr>

<tr>

<td style="text-align:center;">

8481

</td>

<td style="text-align:center;">

1

</td>

<td style="text-align:center;">

John Harvards Simcoe IPA

</td>

<td style="text-align:center;">

7

</td>

</tr>

</tbody>

</table>
