### ISSUE TITLE
RCurl and XML are needed for imgur upload (knitr Suggests them)

### ISSUE THREAD

**Issue by emiltb** [tidyverse/reprex#86]
The package worked out of the box for producing simple reprex'es. However, I had to manually install the packages RCurl and XML from CRAN, before being able to produce reprex'es containing plots. These should probably be added to Depends.

**Comment by jennybc** [comment]
I see RCurl and XML are in Suggests for knitr, so I suppose that's how they should be handled here. This is not about producing plots, but rather about the automatic imgur upload.

I suspect you could have made a figure but stored it locally with this example in the help for `reprex()`:

```r
# write reprex to file AND keep figure local too, i.e. don't post to imgur
reprex({
  #' Some prose
  ## regular comment
  (x <- 1:4)
  median(x)
  plot(x)
  }, outfile = "blarg", opts_knit = list(upload.fun = identity))
list.files(pattern = "blarg")
unlink(list.files(pattern = "blarg"), recursive = TRUE)
```

**Comment by jennybc** [comment]
I've successfully experimented with catching this specific error, but it just seems very fragile and special case-y. I've added something to the documentation of `reprex()` and have raised the issue in knitr (https://github.com/yihui/knitr/issues/1436) that `knitr::imgur_upload()` could possibly check for the suggested packages and emit an informative message if not found.

**Comment by jennybc** [comment]
Snippet re: how to catch these specific errors from the render.  The input source for the reprex is just `plot(1:10)`. The `tmp_lib` contains all the packages needed by reprex except httr/xml2 (or RCurl/XML).

``` r
input <- "foo_reprex.R"
x <- callr::r_safe(
  function(input) {
    tryCatch(
      rmarkdown::render(input, quiet = TRUE),
      error = function(e) {
        if (grepl("RCurl|XML|httr|xml2", conditionMessage(e))) {
          return(e)
        }
        stop(e)
      }
    )
  },
  args = list(input = input),
  libpath = c(tmp_lib, .Library),
  show = TRUE
)
```

Presumably you would still throw the error, but with a better message. Above I just return to prove that it's been caught.
