### ISSUE TITLE
ggplot which errors, generates an empty imgur placeholder

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/reprex#88]
A `ggplot` which errors, generates an empty space due to an imgur placeholder...

``` r
x <- 1
library(ggplot2)
ggplot(df, aes(x, y)) + geom_point()
#> Error in if (is.waive(data) || empty(data)) return(cbind(data, PANEL = integer(0))): missing value where TRUE/FALSE needed
```

![](http://i.imgur.com/tQORbOF.png)

...which is inconvenient if you have more text or code after the plot attempt. The imgur placeholder needs to be deleted manually.

On the other hand, a `plot` which errors does not generate a placeholder

``` r
plot(y)
#> Error in plot(y): object 'y' not found
```

...which is much better!

``` r
y
#> Error in eval(expr, envir, enclos): object 'y' not found
```

**Comment by jennybc** [comment]
Happily, this seems to no longer be the case, due to changes in ggplot2 and/or knitr.

```r
reprex(
  {
    ggplot2::ggplot(foofy, aes(x = hi, y = yo)) + geom_point()
    1:4
  },
  outfile = "foo"
)
```

produces this markdown, which has no imgur placeholder.

```
ggplot2::ggplot(foofy, aes(x = hi, y = yo)) + geom_point()
#> Error in ggplot2::ggplot(foofy, aes(x = hi, y = yo)): object 'foofy' not found
1:4
#> [1] 1 2 3 4
```
