### ISSUE TITLE
inline comments not always preserved

### ISSUE THREAD

**Issue by restonslacker** [tidyverse/reprex#91]
with reprex 0.1.1, i noticed that the output does not contain all of the input comments.

running:
```r
reprex::reprex({
 a <- 1 #this is a comment
 b <- 2 #this is a second comment
},venue = "gh", outfile = "reprex")
```

produces:

``` r
a <- 1 #this is a comment
b <- 2                   
```

which contains one comment but not the other.  This seems to occur when there are no other commands following a comment as illustrated by:

```r
reprex::reprex({
 a <- 1 #this is a comment
 b <- 2 #this is a second comment
 c <- 3 #This is the third comment
},venue = "gh", outfile = "reprex")
```

``` r
a <- 1 #this is a comment       
b <- 2 #this is a second comment
c <- 3                          
```

**Comment by jennybc** [comment]
Yeah, this is actually a limitation from the underlying tools in R. I capture code in this case using [`srcref`s](https://stat.ethz.ch/R-manual/R-devel/library/base/html/srcfile.html). And [comments tend to get dropped](https://stat.ethz.ch/pipermail/r-devel/2009-March/052746.html).

If you really want that trailing comment, you can't provide as expression. You can provide as a string or character vector. For example,

```
reprex::reprex(input = c("a <- 1 #this is a comment",
                         "b <- 2 #this is a second comment",
                         "c <- 3 #This is the third comment"))
```

produces

``` r
a <- 1 #this is a comment
b <- 2 #this is a second comment
c <- 3 #This is the third comment
```

**Comment by restonslacker** [comment]
Ok.  Thanks for the info!

**Comment by jennybc** [comment]
OK I am going to fix this.

**Comment by jennybc** [comment]
After the fix, this input:

```r
reprex::reprex({
 a <- 1 #this is a comment
 b <- 2 #this is a second comment
})
```

yields this output:

``` r
a <- 1 #this is a comment
b <- 2 #this is a second comment
```
